# Dependabot config file

version: 2
updates:
  # Maintain the workflow dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain the poetry (parsers) dependencies.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain the web npm dependencies.
  - package-ecosystem: "npm"
    directory: "/web/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/web/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  # Maintain the mockserver npm dependencies.
  - package-ecosystem: "npm"
    directory: "/mockserver/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  # Maintain the mobile app npm dependencies.
  - package-ecosystem: "npm"
    directory: "/mobileapp/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
