dependencies:
  - poetry.lock
  - pyproject.toml

frontend 🎨:
  - web/src/**/*

translations 🗣:
  - web/public/locales/**/*

javascript:
  - .**/*.js

python:
  - .**/*.py

parser:
  - parsers/**/*

science:
  - config/co2eq_parameters.json

mobile app 📱:
  - mobileapp/**/*
