name: Data Issue
description: Use this form if you believe there is a issue with the data on the app.
title: "[Data Issue]: "
labels: ["data", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file this issue.
  - type: dropdown
    id: where-is-the-problem
    attributes:
      label: On what platform are you seeing the problem?
      description: Please select the platforms where the problem is seen.
      multiple: true
      options:
        - "Android"
        - "iOS"
        - "Web"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: if-other-platform
    attributes:
      label: If other, please specify
      description: Please specify the other platform.
      placeholder: e.g. "Web App or Android TV"
    validations:
      required: false
  - type: textarea
    id: what-is-the-problem
    attributes:
      label: What is the problem?
      description: |
        What appears to be the problem with the data?
        Please provide as much detail as possible.
    validations:
      required: true
