bounding_box:
  - - 112.41944420700008
    - -35.637872002999956
  - - 129.50011656788791
    - -13.223565362999949
capacity:
  solar: 1884
  wind: 491
contributors:
  - jarek
  - corradio
  - MariusKroon
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 497.7064962360909
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 480.25795166959756
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 446.23952795479966
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 412.9192833104802
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 396.7337616029545
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 497.7064962360909
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 480.25795166959756
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 446.23952795479966
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 412.9192833104802
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 396.7337616029545
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 464.4462819896642
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 464.4462819896642
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004639449252483445
        coal: 0.377554629878886
        gas: 0.29561421498718554
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.00022033458216732456
        solar: 0.15436457187453376
        unknown: 0.0
        wind: 0.167605516369052
flag_file_name: au.png
parsers:
  price: OPENNEM.fetch_price
  production: OPENNEM.fetch_production
timezone: null
