bounding_box:
  - - 143.33716881600026
    - -44.1412899719998
  - - 148.98454837300017
    - -39.07146575299984
capacity:
  battery storage: 0
  biomass: 2
  coal: 0
  gas: 372
  hydro: 2361
  hydro storage: 0
  nuclear: 0
  oil: 48
  solar: 187
  wind: 567
contributors:
  - brandongalbraith
  - jarek
  - corradio
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 59.68143335393224
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 59.68143335393224
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 85.52620014694612
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 85.52620014694612
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 1.0615426265846452e-05
        biomass: 0.0
        coal: 0.01852569002060805
        gas: 0.007925200552757057
        geothermal: 0.0
        hydro: 0.7966582553558718
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 2.698608490597352e-09
        solar: 0.019185244328288657
        unknown: 0.0
        wind: 0.1577172461422861
flag_file_name: au.png
parsers:
  price: OPENNEM.fetch_price
  production: OPENNEM.fetch_production
timezone: null
