bounding_box:
  - - -70.56240800699987
    - 11.917669989000046
  - - -69.37682044199994
    - 13.132147528000104
capacity:
  oil: 257.88
  wind: 30
contributors:
  - pascalheraud
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 337.32822273996004
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 326.3041338707095
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 343.28017347038013
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 337.3545610645565
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 337.32822273996004
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 326.3041338707095
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 343.28017347038013
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 337.3545610645565
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 542.2158586094773
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 542.2158586094773
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.8300134466816113
        solar: 0.012112561598734299
        unknown: 0.0007195554431291911
        wind: 0.15728253495460173
flag_file_name: aw.png
parsers:
  production: AW.fetch_production
timezone: America/Aruba
