bounding_box:
  - - 15.7500260759
    - 42.65
  - - 19.59976
    - 45.2337767604
capacity:
  coal: 1888
  hydro: 1747
  hydro storage: 440
  wind: 135
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 655.5226783024217
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 559.2041366058976
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 485.14253140275395
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 517.074692435988
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 480.1543275633537
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 655.5226783024217
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 559.2041366058976
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 485.14253140275395
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 517.074692435988
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 480.1543275633537
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 525.6400113137106
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 525.6400113137106
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 28.8
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0008101253778327626
        coal: 0.612657169615375
        gas: 0.003107803479767005
        geothermal: 8.197788663093253e-06
        hydro: 0.3227411083372364
        hydro discharge: 0.014647812574099956
        nuclear: 0.008349341608582412
        oil: 9.543268497196546e-05
        solar: 0.0015990720292777627
        unknown: 0.014963235050218796
        wind: 0.02102130515240021
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
timezone: Asia/Bahrain
