bounding_box:
  - - 87.52178959200009
    - 20.23871491100003
  - - 93.14285119700017
    - 27.123544007000064
capacity:
  coal: 1768
  gas: 11476
  hydro: 230
  oil: 7619
  solar: 229
contributors:
  - systemcatch
  - alixunderplatz
  - MuffinCompiler
parsers:
  consumption: ERP_PGCB.fetch_consumption
  production: ERP_PGCB.fetch_production
  productionCapacity: EMBER.fetch_production_capacity
timezone: Asia/Dhaka
