bounding_box:
  - - 22.3805257504
    - 41.2344859889
  - - 28.5580814959
    - 44.2349230007
capacity:
  battery storage: 0
  biomass: 81
  coal: 4475
  gas: 1266
  geothermal: 0
  hydro: 2737
  hydro storage: 931
  nuclear: 2080
  oil: 0
  solar: 1313
  wind: 705
contributors:
  - yurukov
  - ultibo
  - systemcatch
  - bogomil
  - Pantkowsky
  - MindFreeze
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 379.72259935750475
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 366.69590025426896
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 381.85747217591825
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.0712022617892
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 328.3820761115468
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 292.8178475978023
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 323.59920945545076
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1057.262766
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 481.60707
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 379.72259935750475
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 366.69590025426896
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 381.85747217591825
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.0712022617892
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 328.3820761115468
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 292.8178475978023
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 323.59920945545076
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 477.07779709278503
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 1067.4905370000001
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 601.60707
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 477.07779709278503
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1124.903938
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.73333333
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005333889716478454
        coal: 0.38710202274631533
        gas: 0.08937288323677252
        geothermal: 0.00013104445173717534
        hydro: 0.11820736536137054
        hydro discharge: 0.0022523616083678093
        nuclear: 0.3410272099231561
        oil: 6.578450159860945e-06
        solar: 0.02533934134079494
        unknown: 6.264899781249798e-05
        wind: 0.031108431437867408
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: BG.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: null
