bounding_box:
  - - -70.1664922699999
    - -23.397257587999945
  - - -56.965660766999946
    - -9.179821471999972
capacity:
  biomass: 122.72
  hydro: 734.85
  nuclear: 0
  solar: 165.08
  unknown: 2484.39
  wind: 131.4
contributors:
  - igorarduin
  - corradio
  - skovhus
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 451.29818758070206
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 402.3145961918597
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 363.3150433212974
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 375.3247374394167
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 367.8411069030223
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 451.29818758070206
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 402.3145961918597
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 363.3150433212974
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 375.3247374394167
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 367.8411069030223
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 318.5106507265494
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 318.5106507265494
    unknown:
      _url: https://www.iea.org/fuels-and-technologies/electricity
      source: IEA 2020; assumes 1.3% oil, 96.0% gas, 2.6% biomass
      value: 485
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0005477671029211332
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.3105717083860671
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0036478389888090416
        unknown: 0.6396800719053272
        wind: 0.045488099087533505
parsers:
  generationForecast: BO.fetch_generation_forecast
  production: BO.fetch_production
timezone: America/La_Paz
