capacity:
  hydro: 109298
  nuclear: 1990
  solar: 7525
  unknown: 39437
  wind: 24506
contributors:
  - alexanmtz
  - corradio
  - systemcatch
  - nessie2013
  - VIKTORVAV99
subZoneNames:
  - BR-CS
  - BR-N
  - BR-NE
  - BR-S
estimation_method: RECONSTRUCT_BREAKDOWN
