_comment: biomass includes 24.4 MW of biogas and 6.6 MW of biomass. gas includes 1273
  CHP
bounding_box:
  - - 23.1994938494
    - 51.3195034857
  - - 32.6936430193
    - 56.1691299506
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 140.0
  gas:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 9720.0
  hydro:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 100.0
  nuclear:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 1170.0
  solar:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 270.0
  wind:
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 120.0
contributors:
  - admetny
country: BY
fallbackZoneMixes:
  _source: https://ourworldindata.org/grapher/electricity-prod-source-stacked?time=earliest..latest&country=~BLR
  powerOriginRatios:
    value:
      gas: 0.98
      hydro: 0.01
      unknown: 0.01
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: EMBER.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
timezone: Europe/Minsk
