bounding_box:
  - - -95.66119498965699
    - 41.229466804384714
  - - -73.84780324445131
    - 57.36127350500004
capacity:
  biomass: 296
  coal: 0
  gas: 10515
  hydro: 8918
  nuclear: 13089
  solar: 478
  wind: 4783
contributors:
  - corradio
  - jarek
  - scriptator
  - felixvanoost
  - misterclean
  - christopheradlam
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.622565842572392
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 24.844900512830517
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.724691722166398
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 32.541670188589464
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.622565842572392
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 24.844900512830517
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.724691722166398
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 32.541670188589464
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 57.47323263502428
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 57.47323263502428
    nuclear:
      datetime: '2013-01-01'
      source: Mallia, E., Lewis, G. "Life cycle greenhouse gas emissions of electricity
        generation in the province of Ontario, Canada." (2013)
      value: 4.8
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 5.246005859666389e-10
        biomass: 0.003308911750891661
        coal: 3.5777460191161355e-05
        gas: 0.08659659371046442
        geothermal: 7.324173609502802e-07
        hydro: 0.2684266723798568
        hydro discharge: 7.494294085237698e-10
        nuclear: 0.5549845749984755
        oil: 8.643169368504636e-07
        solar: 0.004738808598367428
        unknown: 2.8767372446770864e-05
        wind: 0.08265783000861422
flag_file_name: ca.png
parsers:
  price: CA_ON.fetch_price
  production: CA_ON.fetch_production
sources:
  ? "Mallia, E., Lewis, G. \"Life cycle greenhouse gas emissions of electricity generation\
    \ in the province of Ontario, Canada.\" Int J Life Cycle Assess 18, 377\u2013\
    391 (2013)"
  : link: https://doi.org/10.1007/s11367-012-0501-0
timezone: America/Toronto
