bounding_box:
  - - -110.49997270417693
    - 48.49261789994816
  - - -100.86433964677866
    - 60.50005890629359
capacity:
  biomass: 16
  coal: 1389
  gas: 2160
  hydro: 864
  solar: 82
  wind: 617
  unknown: 26
contributors:
  - VIKTORVAV99
disclaimer: The hourly production mix is estimated based on the daily average production mix.
timezone: America/Regina
parsers:
  production: CA_SK.fetch_production
  consumption: CA_SK.fetch_consumption
