bounding_box:
  - - 5.9559111595
    - 45.8179931641
  - - 10.4920501709
    - 47.808380127
capacity:
  biomass: 635
  coal: 0
  gas: 289.6
  geothermal: 0
  hydro: 11184.2
  hydro storage: 4485
  nuclear: 3014.6
  oil: 0.4
  solar: 3135.8
  wind: 88.6
contributors:
  - corradio
  - postronium
  - Kikof2
  - KabelWlan
disclaimer: Data for the electricity consumption and generation mix is based on estimates
  stemming from different data sources. As such, it may diverge from aggregated public
  statistics of the Swiss Federal Office for Energy.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 149.25076294580958
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 140.2912162025784
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 136.54216320191617
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 93.56994370877608
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 77.04689455842045
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 67.79765744800171
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 92.45529931962075
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 149.25076294580958
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 140.2912162025784
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 136.54216320191617
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 93.56994370877608
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 77.04689455842045
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 67.79765744800171
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 92.45529931962075
    unknown:
      _comment:
        'Source ENTSOE, Swiss government and Electricity Maps: https://github.com/electricitymaps/electricitymaps-contrib/pull/2898
        and https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E/'
      source: 52% hydro storage, 48% unknown thermal
      value: 288
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 113.07156762843732
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 113.07156762843732
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 29.5
    unknown:
      _comment:
        'Source ENTSOE, Swiss government and Electricity Maps: https://github.com/electricitymaps/electricitymaps-contrib/pull/2898
        and https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E/'
      source: 52% hydro storage, 48% unknown thermal
      value: 383
estimation_method: RECONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.024581474757886437
        coal: 0.05343819129903392
        gas: 0.031300695923300426
        geothermal: 0.00014280168626957948
        hydro: 0.31566258338812986
        hydro discharge: 0.07615662484729141
        nuclear: 0.3132050108861508
        oil: 0.0013375503530846803
        solar: 0.05161765983320916
        unknown: 0.07506256733465201
        wind: 0.05749727636098628
isLowCarbon:
  hydro discharge:
    _comment: Average share of electricity coming from low carbon sources in 2021
    source: Electricity Maps, https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E
    value: 0.894
  unknown:
    _comment: Around 50% of unknown in CH is made up of hydro discharge, which is
      in turn mostly made up of low-carbon.
    source: Electricity Maps, https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E
    value: 0.465
isRenewable:
  hydro discharge:
    _comment: Average share of electricity coming from renewable sources in 2021
    source: Electricity Maps, https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E
    value: 0.5771
  unknown:
    _comment: Around 50% of unknown in CH is made up of hydro discharge, which is
      in turn half made up of renewables.
    source: Electricity Maps, https://docs.google.com/spreadsheets/d/1FLHQ6e9Es08BIqX654BM3SEb_fuAk4k4O-6cmRXyw_E
    value: 0.3
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: CH.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: Europe/Zurich
