bounding_box:
  - - -74.90721594999991
    - -44.54499811646991
  - - -66.51396683799987
    - -17.006588197999946
capacity:
  battery storage: 0
  biomass: 438.61
  coal: 4637.89
  gas: 3805.02
  geothermal: 51.4
  hydro: 7246.16
  hydro storage: 0
  nuclear: 0
  oil: 4052.4
  solar: 5439.14
  wind: 3834.25
contributors:
  - systemcatch
  - alixunderplatz
delays:
  production: 24
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 195.02493762305187
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 208.9030408694993
    hydro discharge:
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 195.02493762305187
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 208.9030408694993
    unknown:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 298.9863864
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 367.2459401
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 364.8016099
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 349.6068089
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 351.9679562
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 250.68772646613445
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 250.68772646613445
    unknown:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 345.5180312
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 424.6700811
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 424.370115
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 408.9363915
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average. https://docs.google.com/spreadsheets/d/1-iXUGhAM_9Ft5ejlNVxaqaAwG8Octh3gSjU-dm4e96o/edit#gid=0
        value: 415.2803301
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 5.584174914636865e-06
        coal: 9.833998483134234e-05
        gas: 0.0045042703186954055
        geothermal: 0.0039665849279413475
        hydro: 0.20190823746388056
        hydro discharge: 3.837562257680779e-05
        nuclear: 0.0005286543131162734
        oil: 0.000125783013005312
        solar: 0.1310421022647695
        unknown: 0.5690886071472351
        wind: 0.08868521298423133
parsers:
  production: CL.fetch_production
timezone: America/Santiago
