timezone: America/Bogota
capacity:
  biomass: 397
  coal: 1612
  gas: 2491
  hydro: 12549
  nuclear: 0
  oil: 1346
  solar: 297
  wind: 18
contributors:
  - lav-julien
  - alixunderplatz
parsers:
  consumption: CO.fetch_consumption
  production: CO.fetch_production
  price: CO.fetch_price
delays:
  production: 48
