_comment: Hydro capacities from Fraunhofer include capacities in AT, CH, LU which
  are directly connected to the German grid. Fraunhofer has no values for geothermal
  and unknown - these are from BNetz
bounding_box:
  - - 5.8227539063
    - 47.2643200803
  - - 15.0732421875
    - 55.1537662685
capacity:
  battery storage: 2500
  biomass: 9510
  coal: 37940
  gas: 32090
  geothermal: 47
  hydro: 4940
  hydro storage: 9780
  nuclear: 4055
  oil: 4720
  solar: 62510
  unknown: 3700
  wind: 64900
contributors:
  - corradio
  - bohne13
  - chiefymuc
  - nessie2013
  - IV1T3
  - sin
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 410.61597076961647
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 401.58834470914496
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 379.7331032720702
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 348.0320172867049
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 290.7171735859323
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.5320897311558
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 297.22743966244326
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1073.03112
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 540.5939971
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 410.61597076961647
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 401.58834470914496
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 379.7331032720702
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 348.0320172867049
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 290.7171735859323
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.5320897311558
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 297.22743966244326
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 419.4076679907016
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 1152.3866810000002
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 660.5939971
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 419.4076679907016
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1124.903938
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 35.11666667
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08805466802817893
        coal: 0.28735168388385385
        gas: 0.10615241723477183
        geothermal: 0.00036413224657512883
        hydro: 0.04287556898424212
        hydro discharge: 0.0164355327077437
        nuclear: 0.1401563145648876
        oil: 0.006272807148984585
        solar: 0.08836752038748727
        unknown: 0.009456530539935847
        wind: 0.2145180402240008
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Berlin
