bounding_box:
  - - 14.7
    - 54.9
  - - 15.2
    - 55.2
capacity:
  wind: 30
contributors:
  - corradio
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 21.323887100818244
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 18.300449778386067
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 14.42858200867362
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 20.312965257003416
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 21.323887100818244
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 18.300449778386067
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 14.42858200867362
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 20.312965257003416
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 59.77742866645506
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 62.281430999146735
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 49.98138836037956
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 60.20516133951661
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        IPCC 2014
      value: 828.794608
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 59.77742866645506
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 62.281430999146735
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 49.98138836037956
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 60.20516133951661
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 34.3
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.1449798961536152
        coal: 0.0032586735750533384
        gas: 0.0014103206689109122
        geothermal: 0.0
        hydro: 0.1855284168266927
        hydro discharge: 2.759759954804642e-05
        nuclear: 0.17253308464448483
        oil: 4.269539823507714e-05
        solar: 0.07112974915840801
        unknown: 0.031903119190503086
        wind: 0.389121692914206
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.11722444990597843
        coal: 0.0007436246435905025
        gas: 0.0008594296620501758
        geothermal: 0.0
        hydro: 0.18877070777907975
        hydro discharge: 0.0006405859299980615
        nuclear: 0.09851550581260458
        oil: 1.6449863188607168e-05
        solar: 0.10059101431773891
        unknown: 0.02320338984248196
        wind: 0.46961352005172713
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.1509590079414353
        coal: 0.0014267158305035338
        gas: 0.0010663873757632365
        geothermal: 0.0
        hydro: 0.20395406816353634
        hydro discharge: 0.0006876170835335339
        nuclear: 0.1268197224006781
        oil: 4.124579579012153e-05
        solar: 0.08542267762955444
        unknown: 0.032372248705670216
        wind: 0.3976210461531817
parsers:
  price: ENTSOE.fetch_price
  production: DK_BHM.fetch_production
timezone: Europe/Copenhagen
