bounding_box:
  - - 7.60472
    - 54.509132
  - - 13.30324
    - 57.751949
capacity:
  biomass: 2391
  coal: 3165
  gas: 1621
  geothermal: 0
  hydro: 7
  hydro storage: 0
  nuclear: 0
  oil: 997
  solar: 1536
  wind: 6949
contributors:
  - corradio
  - Manu1400
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 845.5332093
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 336.9719859
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1193.417464
  lifecycle:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 254.1851485
    coal:
      datetime: '2020-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 914.3278173
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 456.9719859
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1437.417464
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 35.98888889
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
subZoneNames:
  - DK-DK1
  - DK-DK2
  - DK-BHM
timezone: Europe/Copenhagen
