bounding_box:
  - - 7.60472
    - 54.509132
  - - 13.30324
    - 57.751949
capacity:
  biomass: 2391
  coal: 3165
  gas: 1621
  geothermal: 0
  hydro: 7
  hydro storage: 0
  nuclear: 0
  oil: 997
  solar: 1536
  wind: 6949
contributors:
  - corradio
  - Manu1400
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
subZoneNames:
  - DK-DK1
  - DK-DK2
  - DK-BHM
timezone: Europe/Copenhagen
