bounding_box:
  - - -71.9451120673
    - 17.598564358
  - - -68.3179432848
    - 19.8849105901
capacity:
  biomass: 30
  coal: 950
  gas: 678
  hydro: 623
  oil: 1938
  solar: 188
  wind: 370
contributors:
  - systemcatch
  - nessie2013
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 378.1402482059858
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 377.6492216249728
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 403.853052112231
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 378.1402482059858
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 377.6492216249728
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 403.853052112231
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 543.3047882482156
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 543.3047882482156
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.010134892208187264
        coal: 0.3013204395897952
        gas: 0.3932114794705303
        geothermal: 0.0
        hydro: 0.06850952962979008
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.11564795638695256
        solar: 0.02338202747619552
        unknown: 0.032487597556916416
        wind: 0.05530607768163253
parsers:
  production: DO.fetch_production
timezone: America/Santo_Domingo
