bounding_box:
  - - 23.3397953631
    - 57.4745283067
  - - 28.1316992531
    - 59.6110903998
capacity:
  biomass: 147
  coal: 1371
  gas: 119
  geothermal: 0
  hydro: 4
  hydro storage: 0
  nuclear: 0
  oil: 52
  solar: 370
  unknown: 13
  wind: 329
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 452.5138930783827
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 528.3237886653721
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 570.8698425215212
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 544.6475386390938
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 386.16398340587193
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 240.6908387630035
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 317.99144771844584
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 832.9110972
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 481.60707
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 452.5138930783827
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 528.3237886653721
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 570.8698425215212
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 544.6475386390938
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 386.16398340587193
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 240.6908387630035
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 317.99144771844584
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 861.8244316140375
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 937.8668366210883
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 1093.4963213535773
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 1047.362794719253
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 684.482036048848
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 435.24079765194443
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 573.434075885782
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 892.9110972
    gas:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 601.60707
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 861.8244316140375
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 937.8668366210883
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 1093.4963213535773
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 1047.362794719253
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 684.482036048848
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 435.24079765194443
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 573.434075885782
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 1124.903938
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 36.5
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07825813517406571
        coal: 0.5438351196868192
        gas: 0.054950698589991
        geothermal: 9.60440525758009e-05
        hydro: 0.11228718093435679
        hydro discharge: 5.745097691011445e-06
        nuclear: 0.11645326097763176
        oil: 0.0023514948725674367
        solar: 0.000745046813796597
        unknown: 0.031364938410423225
        wind: 0.059854272564804
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0653806844864985
        coal: 0.6544591273779583
        gas: 0.04768093739994738
        geothermal: 0.0
        hydro: 0.04678972941472107
        hydro discharge: 2.4749409242509365e-06
        nuclear: 0.07004313177412391
        oil: 0.0009393978459117481
        solar: 0.0007585065337275649
        unknown: 0.05084360992876636
        wind: 0.06311522980941314
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08780117594374816
        coal: 0.33219021567980245
        gas: 0.060596221936973116
        geothermal: 0.0
        hydro: 0.13585989764715717
        hydro discharge: 0.00025040290242526884
        nuclear: 0.17710022340971948
        oil: 0.00017893491345372163
        solar: 0.008985547436410639
        unknown: 0.07486013335497879
        wind: 0.1224969922378381
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Tallinn
