bounding_box:
  - - -18.66722571499986
    - 27.14223867400007
  - - -17.379261847999913
    - 28.352036851000108
capacity:
  hydro storage: 11.32
  oil: 11.78
  wind: 11.5
contributors:
  - hectorespert
  - systemcatch
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.04424395347895984
        nuclear: 0.0
        oil: 0.41521711388994126
        solar: 0.0
        unknown: 0.0
        wind: 0.5405265475442473
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.036587326365899994
        nuclear: 0.0
        oil: 0.5372941527579187
        solar: 0.0
        unknown: 0.0
        wind: 0.42612439253626966
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.035028722497975284
        nuclear: 0.0
        oil: 0.47667870325185996
        solar: 0.0
        unknown: 0.0
        wind: 0.48828702439202293
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Atlantic/Canary
