bounding_box:
  - - -18.66722571499986
    - 27.14223867400007
  - - -17.379261847999913
    - 28.352036851000108
capacity:
  hydro storage: 11.32
  oil: 11.78
  wind: 11.5
contributors:
  - hectorespert
  - systemcatch
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        IPCC 2014
      value: 839.306989
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 85.1146852278433
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 106.15959591418171
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 133.81042522350103
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 117.7976781548657
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.04424395347895984
        nuclear: 0.0
        oil: 0.41521711388994126
        solar: 0.0
        unknown: 0.0
        wind: 0.5405265475442473
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.036587326365899994
        nuclear: 0.0
        oil: 0.5372941527579187
        solar: 0.0
        unknown: 0.0
        wind: 0.42612439253626966
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.035028722497975284
        nuclear: 0.0
        oil: 0.47667870325185996
        solar: 0.0
        unknown: 0.0
        wind: 0.48828702439202293
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Atlantic/Canary
