bounding_box:
  - - -15.007069464999915
    - 27.55068594000015
  - - -12.91779537699989
    - 29.74331289300015
contributors:
  - hectorespert
  - systemcatch
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 376.8801597908468
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 361.6464509296587
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 359.9701747201522
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 345.4548264323977
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 376.8801597908468
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 361.6464509296587
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 359.9701747201522
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 345.4548264323977
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 597.6420350396105
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 574.5289013692587
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 577.5550960140915
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 555.4412558744081
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 597.6420350396105
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 574.5289013692587
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 577.5550960140915
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 555.4412558744081
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.06875534009879547
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.8655446755694768
        solar: 0.017026153668998473
        unknown: 0.0
        wind: 0.048597587222609276
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.06072184311056456
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.8354170227417773
        solar: 0.017987347534864837
        unknown: 0.0
        wind: 0.08587409970437061
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.006938024017356822
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.8803032644001699
        solar: 0.021119700622994696
        unknown: 0.0
        wind: 0.09163932036437582
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.8508737999322145
        solar: 0.02155466334462865
        unknown: 0.0
        wind: 0.12757184991542395
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Atlantic/Canary
