bounding_box:
  - - 1.850759311000076
    - 38.76906972900008
  - - 3.974375847000147
    - 40.46877676000017
contributors:
  - hectorespert
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 971.2573613
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 422.8263312
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 560.9141128830634
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 507.7143752914014
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 382.9412306002058
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 403.8061373548075
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1050.5643503
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 560.9141128830634
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 507.7143752914014
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 382.9412306002058
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 403.8061373548075
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07140728939724357
        coal: 0.5146893113935764
        gas: 0.23723450060690102
        geothermal: 0.0
        hydro: 0.03735720571286309
        hydro discharge: 0.0008073306672178719
        nuclear: 0.05966279930855186
        oil: 0.0030056082444168447
        solar: 0.020579064044872995
        unknown: 0.001401334830132856
        wind: 0.054034945491589825
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.06340073594991104
        coal: 0.4068054643061342
        gas: 0.3108718596853416
        geothermal: 0.0
        hydro: 0.03414574179638406
        hydro discharge: 0.0006156026658632377
        nuclear: 0.0796184359332713
        oil: 0.0028766201058085324
        solar: 0.03888174734677931
        unknown: 0.0015378207476836536
        wind: 0.06161051344367634
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.060572282797604404
        coal: 0.06132296314586888
        gas: 0.6343423760365288
        geothermal: 1.6257054904772704e-08
        hydro: 0.04594730885834079
        hydro discharge: 0.0007758083361289596
        nuclear: 0.07847271732104501
        oil: 0.002547857125349843
        solar: 0.048601354356819455
        unknown: 0.0016639176980309386
        wind: 0.06585807995326899
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05550957931144226
        coal: 0.014689744221931686
        gas: 0.7619392959084769
        geothermal: 1.4718285430428863e-08
        hydro: 0.028428130363258888
        hydro discharge: 0.00042688179148144353
        nuclear: 0.04246525109091993
        oil: 0.001439904581944286
        solar: 0.051862260623308246
        unknown: 0.0009315717988908492
        wind: 0.04241750497298361
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Europe/Madrid
