bounding_box:
  - - 0.712168816000087
    - 38.33180940700015
  - - 2.123057488000086
    - 39.618882554000066
contributors:
  - hectorespert
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 411.46578798460877
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 312.186836458822
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 318.5840058632317
    hydro discharge:
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 411.46578798460877
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 312.186836458822
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 318.5840058632317
  lifecycle:
    battery discharge:
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 540.9317310222422
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 426.0422156611445
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 453.2100725466528
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        IPCC 2014
      value: 839.306989
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 540.9317310222422
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 426.0422156611445
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 453.2100725466528
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03595638277832256
        coal: 0.2276881568195444
        gas: 0.3680365680489389
        geothermal: 0.0
        hydro: 0.018168955197287794
        hydro discharge: 0.00029835450831312805
        nuclear: 0.04449836826976153
        oil: 0.250264115131203
        solar: 0.0203597278526854
        unknown: 0.0008587327755785886
        wind: 0.03397180190749793
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05096227691515294
        coal: 0.0648792947386169
        gas: 0.6145378018873535
        geothermal: 0.0
        hydro: 0.03374603824048286
        hydro discharge: 0.0005894340379954379
        nuclear: 0.06175266355455775
        oil: 0.08498871691018557
        solar: 0.03482082023029623
        unknown: 0.001304858533008153
        wind: 0.05227924898461224
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.04171859190170486
        coal: 0.010864983217226025
        gas: 0.6331162111507777
        geothermal: 0.0
        hydro: 0.022450550879772803
        hydro discharge: 0.00031618658833448094
        nuclear: 0.03368710277638138
        oil: 0.18607921932032764
        solar: 0.03688343243774682
        unknown: 0.0007363017570217005
        wind: 0.03424064934833053
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Europe/Madrid
