bounding_box:
  - - 3.303151889000077
    - 39.31647370000019
  - - 4.837087436000104
    - 40.57941315300016
contributors:
  - hectorespert
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 971.2573613
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 422.8263312
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 578.3212608331016
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 555.0080352458373
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 560.0961198553547
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 547.8984196172062
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1050.5643503
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 578.3212608331016
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 555.0080352458373
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 560.0961198553547
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 547.8984196172062
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.33934461443317315
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6327276727259832
        solar: 0.013579422341492658
        unknown: 0.0
        wind: 0.014347612883465652
    - _source: electricityMap, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.48494066234336547
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.4869855450139305
        solar: 0.015792990958275258
        unknown: 0.0
        wind: 0.012280558178375044
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.006679055451115867
        coal: 0.011483508390834464
        gas: 0.3485001758414015
        geothermal: 0.0
        hydro: 0.004437058878364784
        hydro discharge: 7.59876259126433e-05
        nuclear: 0.008649995408821158
        oil: 0.5796266027416296
        solar: 0.024078800290304153
        unknown: 0.00018202615081601038
        wind: 0.016278734083560054
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.009087812591814829
        coal: 0.002667449563312586
        gas: 0.4237573207981387
        geothermal: 0.0
        hydro: 0.0052521897414790865
        hydro discharge: 8.169183186533579e-05
        nuclear: 0.007417653726530078
        oil: 0.5144680592016038
        solar: 0.024228386029099633
        unknown: 0.00015511051314371366
        wind: 0.012883352691178464
flag_file_name: es.png
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
timezone: Europe/Madrid
