bounding_box:
  - - 20.6455928891
    - 59.846373196
  - - 31.5160921567
    - 70.1641930203
capacity:
  biomass: 2790
  coal: 2798
  gas: 1935
  geothermal: 0
  hydro: 3178
  nuclear: 4394
  oil: 1051
  solar: 606
  unknown: 784
  wind: 5121
contributors:
  - corradio
  - nessie2013
  - gadakast
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 143.26585504117497
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 173.41149235776263
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 155.25684347835775
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 173.24492382664192
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 150.24790343884274
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 100.90112575306237
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 133.0175786431113
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 895.6862569
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 684.2607818
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 143.26585504117497
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 173.41149235776263
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 155.25684347835775
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 173.24492382664192
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 150.24790343884274
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 100.90112575306237
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 133.0175786431113
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 204.55475056974853
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 990.5340999
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 804.2607818
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 204.55475056974853
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1124.903938
    wind:
      datetime: '2012-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07640489093224406
        coal: 0.08212925039934067
        gas: 0.048202913988645006
        geothermal: 8.606381348474452e-08
        hydro: 0.2434842684786377
        hydro discharge: 0.00022608692541139144
        nuclear: 0.3395927988762921
        oil: 0.00036141216146757664
        solar: 0.0002992819793695037
        unknown: 0.09186607611561888
        wind: 0.1174699205578574
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
  productionPerUnit: ENTSOE.fetch_production_per_units
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Helsinki
