bounding_box:
  - - -8.144154425999943
    - 60.894110419000086
  - - -5.775786912999905
    - 62.89891185100005
capacity:
  biomass: 1.3
  hydro: 40.6
  oil: 99.7
  solar: 0.24
  unknown: 0.1
  wind: 43.5
contributors:
  - corradio
  - q--
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 217.63610540948878
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 208.79211577574483
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 240.62341395193437
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 250.88893946655722
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 248.37990993773258
    hydro discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 217.63610540948878
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 208.79211577574483
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 240.62341395193437
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 250.88893946655722
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 248.37990993773258
    unknown:
      source: Tidal (IPCC 2014)
      value: 0
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 357.4756190182087
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 343.635256065452
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 393.25064707281933
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 409.3641592249868
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 408.8110193788959
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        IPCC 2014
      value: 820.0
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 357.4756190182087
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 343.635256065452
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 393.25064707281933
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 409.3641592249868
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 408.8110193788959
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    unknown:
      source: Tidal (IPCC 2014)
      value: 17
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.2685630274166093
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6178784421667692
        solar: 0.0
        unknown: 0.0
        wind: 0.1133928104338448
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01733172985203319
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.237708660836947
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6117476901021067
        solar: 0.0004114547212078257
        unknown: 1.4446059177202655e-05
        wind: 0.13272450542005115
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  production: FO.fetch_production
timezone: Atlantic/Faroe
