bounding_box:
  - - -8.673837442999911
    - 53.53457265800016
  - - -4.930775519999884
    - 55.81134674700017
capacity:
  biomass: 35
  coal: 514
  gas: 1549
  oil: 316
  solar: 92
  wind: 995
contributors:
  - corradio
  - systemcatch
  - brunolajoie
  - alixunderplatz
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 395.02150311392023
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 403.8066019171408
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 347.2166230243035
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 316.4666549524557
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 286.7554826670641
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 290.046000988274
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 291.012971537
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 395.02150311392023
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 403.8066019171408
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 347.2166230243035
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 316.4666549524557
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 286.7554826670641
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 290.046000988274
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 291.012971537
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 369.21036828210566
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 369.21036828210566
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.13819904765807792
        gas: 0.5126915281813463
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.001295962420769125
        solar: 0.0
        unknown: 0.0
        wind: 0.34781314616395964
flag_file_name: _Northern%20Ireland.png
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: null
