bounding_box:
  - - -3.933338995999918
    - 58.2306989600001
  - - -1.8924861319999025
    - 59.86090729400016
capacity:
  solar: 1.2
  wind: 48
contributors:
  - systemcatch
  - maxbellec
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 500.1418085304128
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 461.82122772629816
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.96951155133394
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.17442286784836
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 500.1418085304128
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 461.82122772629816
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.96951155133394
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.17442286784836
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 93.85874239801099
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 93.85874239801099
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 43.6
    unknown:
      _comment: Source http://www.oref.co.uk/wp-content/uploads/2015/05/Orkney-wide-energy-audit-2014-Energy-Sources-and-Uses.pdf
      source: assumes 95% wind, 5% solar
      value: 13
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02259268626221183
        coal: 0.007282772532766238
        gas: 0.13947111794718392
        geothermal: 0.0
        hydro: 0.007245869764795586
        hydro discharge: 0.0026492579800356775
        nuclear: 0.06617959021392708
        oil: 0.0001476862302695142
        solar: 0.012594741844093696
        unknown: 0.6994951986943484
        wind: 0.04224314715222993
flag_file_name: gb.png
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  production: GB_ORK.fetch_production
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
timezone: null
