_comment: Key should be GB-GBN (see https://en.wikipedia.org/wiki/ISO_3166-2:GB)
bounding_box:
  - - -8.173828125
    - 49.6462914122
  - - 2.1533203125
    - 61.0795442346
capacity:
  biomass: 4528
  coal: 5241
  gas: 39822
  geothermal: 0
  hydro: 1919
  hydro storage: 4309
  nuclear: 5883
  oil: 0
  solar: 13378
  unknown: 4708
  wind: 25097
contributors:
  - corradio
  - lorrieq
  - nessie2013
  - AlexandreCouderc
  - gadakast
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 278.0640883424948
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 275.04179191646847
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 245.19949946255318
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 204.70075828873854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 184.0872287402165
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 164.43078713022896
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 177.32511322487701
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 278.0640883424948
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 275.04179191646847
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 245.19949946255318
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 204.70075828873854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 184.0872287402165
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 164.43078713022896
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 177.32511322487701
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 255.1124326504468
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 255.1124326504468
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 39.72
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07379306674658931
        coal: 0.0218987365449623
        gas: 0.414010831023813
        geothermal: 1.0017835076726296e-06
        hydro: 0.023690266350709928
        hydro discharge: 0.008071839227750715
        nuclear: 0.21407482961189478
        oil: 0.0005519120395752719
        solar: 0.0433534991409621
        unknown: 0.00837941979784435
        wind: 0.19217504222045206
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: GB.fetch_price
  production: ELEXON.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
timezone: null
