_comment: source:http://www.gse.com.ge/for-customers/data-from-the-power-system, gas
  incl. 13 MW of coal
bounding_box:
  - - 39.9550085793
    - 41.0644446885
  - - 46.6379081561
    - 43.553104153
capacity:
  gas: 1189
  hydro: 3439
  nuclear: 0
  wind: 21
contributors:
  - alixunderplatz
  - kruschk
  - tmslaine
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 83.5501373839501
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 116.76524778275963
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 122.09479448781428
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 114.62596612266658
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 83.5501373839501
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 116.76524778275963
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 122.09479448781428
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 114.62596612266658
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 130.3962863832545
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 175.19825289163174
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 179.50050568291232
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 166.28173630004179
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 130.3962863832545
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 175.19825289163174
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 179.50050568291232
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 166.28173630004179
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.777205316274428e-07
        coal: 2.724685101124253e-05
        gas: 0.26030328848642775
        geothermal: 2.4986890238113766e-07
        hydro: 0.6832822123309857
        hydro discharge: 0.0
        nuclear: 0.0014670630850065626
        oil: 0.044179329383378145
        solar: 1.0280434235229039e-05
        unknown: 0.004327610820876799
        wind: 0.007139598843275684
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  production: GE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Asia/Tbilisi
