bounding_box:
  - - -54.708003
    - 2.10212
  - - -51.595232
    - 5.78601
capacity:
  biomass: 1.976
  gas: 80
  hydro: 119.13
  oil: 108
  solar: 44.879
contributors:
  - PETILLON-Sebastien
  - VIKTORVAV99
parsers:
  price: FR_O.fetch_price
  production: FR_O.fetch_production
  productionCapacity: IRENA.fetch_production_capacity
timezone: Europe/Paris
