bounding_box:
  - - 23.018239780000044
    - 34.31500885600016
  - - 26.821136915000068
    - 36.186957098000164
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1523.652468
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 382.5054126
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 439.145806
    coal:
      datetime: '2021-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; EU-ETS, ENTSO-E 2021
      value: 1537.25003
    gas:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 502.5054126
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 1124.903938
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
timezone: null
