bounding_box:
  - - 20.1500159034
    - 34.9199876979
  - - 26.6041955909
    - 41.8269046087
capacity:
  biomass: 106
  coal: 2001
  gas: 5213
  geothermal: 0
  hydro: 2722
  hydro storage: 699
  nuclear: 0
  oil: 0
  solar: 3820
  unknown: 109
  wind: 4150
contributors:
  - corradio
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 431.37862976192986
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 408.63401116697196
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 416.93488620755323
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 395.3038950502768
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 359.1857620213045
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 306.8442445874303
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 284.5154177979549
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1523.652468
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 382.5054126
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 431.37862976192986
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 408.63401116697196
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 416.93488620755323
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 395.3038950502768
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 359.1857620213045
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 306.8442445874303
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 284.5154177979549
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 336.2398737077919
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 1537.25003
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 502.5054126
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 336.2398737077919
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1124.903938
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.1
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.001954257075316571
        coal: 0.1529422988666138
        gas: 0.4404749144060398
        geothermal: 0.001713012885929345
        hydro: 0.10720023545085662
        hydro discharge: 0.01368156398796824
        nuclear: 0.017680586110962224
        oil: 0.00046823154388212965
        solar: 0.0903918240066729
        unknown: 0.0004902429821393064
        wind: 0.17300335635193237
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: null
