bounding_box:
  - - 113.337331576
    - 21.677069403000075
  - - 114.90129642000011
    - 23.06394603200009
capacity:
  coal: 2875
  gas: 3225
  oil: 210
contributors:
  - nessie2013
emissionFactors:
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 435.35999999999996
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 435.35999999999996
estimation_method: CONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.2399999736696371
        gas: 0.4799999308827975
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.27999959078227754
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.0
flag_file_name: hk.png
timezone: Asia/Hong_Kong
