bounding_box:
  - - 16.2022982113
    - 45.7594811061
  - - 22.710531447
    - 48.6238540716
capacity:
  biomass: 300
  coal: 1049
  gas: 4011
  geothermal: 3
  hydro: 58
  hydro storage: 0
  nuclear: 1910
  oil: 420
  solar: 1829
  unknown: 69
  wind: 323
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 250.73878781343313
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 246.20095625769338
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 236.85424099026892
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 238.95739664926998
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 214.75093818688885
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 199.91373439726587
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 206.7899846183766
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 1144.916957
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 455.1593805
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 250.73878781343313
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 246.20095625769338
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 236.85424099026892
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 238.95739664926998
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 214.75093818688885
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 199.91373439726587
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 206.7899846183766
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 311.972963238646
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 1157.920756
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 575.1593805
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 311.972963238646
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1124.903938
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 30.66666667
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03356426756883051
        coal: 0.13795130044889675
        gas: 0.2101781222325038
        geothermal: 4.6310379616579276e-05
        hydro: 0.06775191517293304
        hydro discharge: 0.007525310766476084
        nuclear: 0.4236851870261152
        oil: 0.002751021427517595
        solar: 0.05149199524363666
        unknown: 0.03587599482246664
        wind: 0.02918964211120518
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Budapest
