bounding_box:
  - - 67.434082
    - 11.393879
  - - 100.327148
    - 27.664069
capacity:
  battery storage: 0
  biomass: 0
  coal: 35887.00
  gas: 80.0
  geothermal: 0
  hydro: 5987.75
  hydro storage: 0
  nuclear: 0
  oil: 92.71
  solar: 0
  unknown: 0
  wind: 0

timezone: Asia/Kolkata