bounding_box:
  - - 67.434082
    - 11.393879
  - - 100.327148
    - 27.664069
capacity:
  battery storage: 0
  biomass: 513.24
  coal: 35887.00
  gas: 80.0
  geothermal: 0
  hydro: 6331.74
  hydro storage: 0
  nuclear: 0
  oil: 92.71
  solar: 917.72
  unknown: 0
  wind: 0

timezone: Asia/Kolkata