bounding_box:
  - - 72.79941
    - 15.613079
  - - 80.661984
    - 22.105644
capacity:
  biomass: 2597
  coal: 23856
  gas: 3207.08
  hydro: 3047
  nuclear: 1400
  oil: 0
  solar: 2295
  unknown: 480.55
  wind: 5010.8
contributors:
  - GitMatze
  - alixunderplatz
  - systemcatch
  - Manu1400
  - gopikrishna1793
estimation_method: RECONSTRUCT_BREAKDOWN
flag_file_name: in.png
parsers:
  production: IN_MH.fetch_production
timezone: Asia/Kolkata
