bounding_box:
  - - 72.79941
    - 15.613079
  - - 80.661984
    - 22.105644
capacity:
  biomass: 2597
  coal: 23856
  gas: 3207.08
  hydro: 3047
  nuclear: 1400
  oil: 0
  solar: 2295
  unknown: 480.55
  wind: 5010.8
contributors:
  - GitMatze
  - alixunderplatz
  - systemcatch
  - Manu1400
  - gopikrishna1793
emissionFactors:
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 728.9448907770259
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 728.9448907770259
estimation_method: RECONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.8684780403186796
        gas: 0.030108537753421663
        geothermal: 0.0
        hydro: 0.03485066094522507
        hydro discharge: 0.0
        nuclear: 0.020572231651068022
        oil: 0.0
        solar: 0.013250569731097632
        unknown: 0.0
        wind: 0.03273995683843821
flag_file_name: in.png
parsers:
  production: IN_MH.fetch_production
timezone: Asia/Kolkata
