bounding_box:
  - - 60.754395
    - 20.797201
  - - 93.647461
    - 35.978006
capacity:
  biomass:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 3377.9
  coal:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 44285.0
  diesel:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 0.0
  gas:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 5994.96
  hydro:
    datetime: '2023-12-01'
    source: cea.nic.in, mnre.gov.in
    value: 21469.8
  nuclear:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 1620.0
  solar:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 25012.2
  wind:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 5193.4
contributors:
  - corradio
  - gopikrishna1793
  - hectorespert
  - pierresegonne
  - sahitya-pavurala
  - willbeaufoy
  - mathilde-daugy
emissionFactors:
  direct:
    unknown:
      source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
      value: 45
  lifecycle:
    unknown:
      source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
      value: 192
isLowCarbon:
  unknown:
    value: 0.92
isRenewable:
  unknown:
    value: 0.92
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
  productionCapacity: CEA.fetch_production_capacity
timezone: Asia/Kolkata
