bounding_box:
  - - 73.740234
    - 17.936929
  - - 106.633301
    - 33.486435
capacity:
  battery storage: 0
  biomass: 0
  coal: 750.0
  gas: 1664.95
  geothermal: 0
  hydro: 2027.00
  hydro storage: 0
  nuclear: 0
  oil: 36
  solar: 0
  unknown: 0
  wind: 0

timezone: Asia/Kolkata