bounding_box:
  - - 62.775879
    - 6.031311
  - - 95.668945
    - 22.755921
capacity:
  biomass: 3734.75
  coal: 43397.5
  gas: 6491.8
  hydro: 13670.43
  nuclear: 3320.0
  oil: 460.49
  solar: 25044.86
  unknown: 0
  wind: 19655.72
contributors:
  - hectorespert
  - gopikrishna1793
  - unitrium
timezone: Asia/Kolkata
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
