bounding_box:
  - - 62.775879
    - 6.031311
  - - 95.668945
    - 22.755921
capacity:
  biomass:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 3740.7
  coal:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 41357.5
  gas:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 6491.8
  hydro:
    datetime: '2023-12-01'
    source: cea.nic.in, mnre.gov.in
    value: 13675.65
  nuclear:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 3320.0
  oil:
    datetime: '2023-12-01'
    source: cea.nic.in
    value: 460.49
  solar:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 26954.5
  wind:
    datetime: '2023-12-01'
    source: mnre.gov.in
    value: 20312.4
contributors:
  - hectorespert
  - gopikrishna1793
  - unitrium
country: IN
delays:
  production: 75
emissionFactors:
  direct:
    unknown:
      - datetime: '2020-01-01'
        source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
        value: 45
  lifecycle:
    unknown:
      - datetime: '2020-01-01'
        source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
        value: 192
isLowCarbon:
  unknown:
    value: 0.92
isRenewable:
  unknown:
    value: 0.92
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
  productionCapacity: CEA.fetch_production_capacity
region: Asia
timezone: Asia/Kolkata
