bounding_box:
  - - 76.5581702012937
    - 23.411047268416667
  - - 85.11243777868054
    - 30.902020574789645
capacity:
  biomass: 2117.3
  coal: 24389
  gas: 1493.14
  hydro: 501.6
  nuclear: 440
  oil: 0
  solar: 1840.3
  wind: 0
contributors:
  - sahitya-pavurala
  - pierresegonne
  - gopikrishna1793
emissionFactors:
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 733.8361105043967
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 733.8361105043967
estimation_method: RECONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 5.7670515633935e-05
        coal: 0.8544716150968797
        gas: 0.06265579424467269
        geothermal: 0.0
        hydro: 0.060552708868732034
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.02226215047275993
        unknown: 0.0
        wind: 0.0
flag_file_name: in.png
parsers: {}
timezone: Asia/Kolkata
