capacity:
  biomass: 10682.36
  coal: 210699.5
  gas: 24879.21
  hydro: 51608.52
  nuclear: 6780
  oil: 509.71
  solar: 56951.33
  wind: 40706.38
contributors:
  - systemcatch
  - gopikrishna1793
emissionFactors:
  lifecycle:
    unknown:
      source: assumes 43% solar PV and 57% wind
      value: 26
fallbackZoneMixes:
  _source: Electricity Maps
  powerOriginRatios:
    value:
      battery discharge: 0
      biomass: 0.0
      coal: 0.739788531237817
      gas: 0.03592277014733543
      geothermal: 0.0
      hydro: 0.1233011541061651
      hydro discharge: 0.0
      nuclear: 0.02956120063948037
      oil: 0.0
      solar: 0.0
      unknown: 0.07142634386920217
      wind: 0.0
parsers:
  production: IN.fetch_production
timezone: Asia/Kolkata
