bounding_box:
  - - 6.1027283120000675
    - 43.24286154752235
  - - 14.394686320000034
    - 47.585214945000075
capacity:
  biomass: 2569.3
  coal: 1750
  gas: 25614.4
  geothermal: 0
  hydro: 12047.4
  hydro storage: 4799.8
  nuclear: 0
  oil: 30
  solar: 9649.7
  wind: 146.2
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 338.0415958776842
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 410.12539362902277
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 405.332897601941
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 346.8524423934995
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.2645328159232
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 271.5739449762081
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 316.8526181348207
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 997.0022828
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 446.1813452
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 338.0415958776842
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 410.12539362902277
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 405.332897601941
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 346.8524423934995
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.2645328159232
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 271.5739449762081
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 316.8526181348207
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 921.1256533
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 374.4052265220053
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
        hotspots of coal power generation."
      value: 1082.9825388
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 566.1813452
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 374.4052265220053
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021; IPCC 2014
      value: 1165.1256533
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.3
    wind:
      datetime: '2014-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.018556180798586393
        coal: 0.02319039861720515
        gas: 0.42018412099051444
        geothermal: 0.0030934474936741836
        hydro: 0.24846696567590265
        hydro discharge: 0.028394495557589106
        nuclear: 0.10205268513729825
        oil: 0.0007809464837634432
        solar: 0.0534540707111529
        unknown: 0.08334501369877219
        wind: 0.018482748670133237
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Rome
