bounding_box:
  - - 7.633799675000148
    - 38.36432526200005
  - - 10.326670769000089
    - 41.76264069200013
capacity:
  biomass: 113.9
  coal: 966
  gas: 995.9
  geothermal: 0
  hydro: 226.4
  hydro storage: 240
  nuclear: 0
  oil: 251
  solar: 973.8
  wind: 1087.5
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 553.1810486798224
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 561.3412372712706
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 471.18479426498527
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 485.17409704187315
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 473.75528646039413
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 997.0022828
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 473.8451586
    hydro discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 553.1810486798224
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 561.3412372712706
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 471.18479426498527
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 485.17409704187315
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 473.75528646039413
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 921.1256533
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 553.1810486798224
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 561.3412372712706
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 471.18479426498527
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 485.17409704187315
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 473.75528646039413
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1082.9825388
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 553.1810486798224
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 561.3412372712706
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 471.18479426498527
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 485.17409704187315
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 473.75528646039413
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02542155826935053
        coal: 0.34159485593959876
        gas: 0.018122732774172402
        geothermal: 0.00012466625225839126
        hydro: 0.028407086811221047
        hydro discharge: 0.01593038031439317
        nuclear: 7.285654820673808e-05
        oil: 0.015052565658023159
        solar: 0.04649785918584718
        unknown: 0.3818776234345052
        wind: 0.1268976508433495
    - _source: electricityMap, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03855936350793357
        coal: 0.35060988537722404
        gas: 0.34371024533541844
        geothermal: 0.0003022423531598494
        hydro: 0.022915344665292877
        hydro discharge: 0.016000750756597546
        nuclear: 0.00010738207643906696
        oil: 0.015005054367549868
        solar: 0.06114859529079358
        unknown: 0.021871425404336425
        wind: 0.12976949799512685
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Rome
