bounding_box:
  - - 126.11
    - 34.39
  - - 129.46
    - 38.61
capacity:
  biomass: 1446
  coal: 37338
  gas: 41828
  hydro: 1806
  hydro storage: 4700
  nuclear: 24431
  oil: 960
  solar: 18709
  wind: 1727
contributors:
  - systemcatch
  - alixunderplatz
  - IV1T3
  - gadakast
emissionFactors:
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.50488607461506
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.50488607461506
    unknown:
      _comment: 'Source: 2020 annual electricity production by IEA'
      _url: https://www.iea.org/fuels-and-technologies/electricity
      source: IEA 2020; assumes 54.1% coal, 36.1% gas, 1.5% oil, 4.4% solar, 0.8%
        wind, 2.2% biofuels, 1.0% other
      value: 644
estimation_method: RECONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0120921028325683
        coal: 0.4272542816069859
        gas: 0.2579648489665236
        geothermal: 0.0
        hydro: 0.005038376106233693
        hydro discharge: 0.0
        nuclear: 0.26098787429280973
        oil: 0.006046050865701088
        solar: 0.02658576522566332
        unknown: 0.0040307004942505865
        wind: 0.0
parsers:
  consumption: KR.fetch_consumption
  price: KR.fetch_price
  production: KR.fetch_production
timezone: Asia/Seoul
