emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    coal:
      datetime: '2022-01-01'
      source: EU-ETS, ENTSO-E 2022
      value: 1045.58
    gas:
      datetime: '2022-01-01'
      source: EU-ETS, ENTSO-E 2022
      value: 449.46
    oil:
      datetime: '2022-01-01'
      source: EU-ETS, ENTSO-E 2022
      value: 925.95
  lifecycle:
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2014-01-01'
        source: IPCC 2014
        value: 820.0
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1105.58
    gas:
      - datetime: '2014-01-01'
        source: IPCC 2014
        value: 490.0
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 569.46
    oil:
      - datetime: '2014-01-01'
        source: EIA 2020/BEIS 2021; IPCC 2014
        value: 650.0
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
sources:
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: Europe/Vaduz
