bounding_box:
  - - 21.0558004086
    - 53.9057022162
  - - 26.5882792498
    - 56.3725283881
capacity:
  biomass: 165
  coal: 0
  gas: 1527
  geothermal: 0
  hydro: 128
  hydro storage: 900
  nuclear: 0
  oil: 0
  solar: 259
  unknown: 37
  wind: 671
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 456.2232591860777
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 458.2067145264293
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 360.76413440271364
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 408.58225605719963
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 460.20444383445204
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 200.67100610475939
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 232.42336519914036
    hydro discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 456.2232591860777
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 458.2067145264293
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 360.76413440271364
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 408.58225605719963
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 460.20444383445204
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 200.67100610475939
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 232.42336519914036
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 456.2232591860777
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 458.2067145264293
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 360.76413440271364
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 408.58225605719963
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 460.20444383445204
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 265.2136626591556
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 307.2126162460251
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        IPCC 2014
      value: 820.0
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 456.2232591860777
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 458.2067145264293
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 360.76413440271364
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 408.58225605719963
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 460.20444383445204
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 265.2136626591556
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 307.2126162460251
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 36.7
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Vilnius
