bounding_box:
  - - 5.67405195478
    - 49.4426671413
  - - 6.24275109216
    - 50.1280516628
capacity:
  biomass: 56.473
  coal: 0
  gas: 11.603
  geothermal: 0
  hydro: 22.977
  hydro storage: 1096
  nuclear: 0
  solar: 268.281942
  unknown: 82.3648
  wind: 138.535
contributors:
  - corradio
  - clawfire
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 178.41865232807453
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1057.262766
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 481.60707
    hydro discharge:
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 178.41865232807453
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 246.79495684659946
    coal:
      datetime: '2020-01-01'
      source: 'IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1117.262766
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 246.79495684659946
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.13683191062360203
        coal: 0.15346706775115065
        gas: 0.1264632383266689
        geothermal: 0.00021169172553920596
        hydro: 0.04680064456188765
        hydro discharge: 0.011667630183953117
        nuclear: 0.22906003172926262
        oil: 0.0038101838284090024
        solar: 0.13108021125524777
        unknown: 0.016793999410309606
        wind: 0.14381581350105957
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: null
