bounding_box:
  - - 21.0558004086
    - 55.61510692
  - - 28.1767094256
    - 57.9701569688
capacity:
  biomass: 164
  gas: 1162
  hydro: 1588
  solar: 14
  wind: 87
contributors:
  - corradio
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 309.9648151430727
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 329.1895744469897
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 247.55474693754593
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 328.4925818714251
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 275.77287856764997
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 205.40961010031214
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 224.5448269708235
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1057.262766
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 481.60707
    hydro discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 309.9648151430727
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 329.1895744469897
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 247.55474693754593
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 328.4925818714251
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 275.77287856764997
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 205.40961010031214
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 224.5448269708235
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 880.903938
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 493.7680899731894
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 514.2989603956713
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 409.0929869387971
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 525.1871186670132
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 403.54356709907603
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 298.8199728907811
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 340.34978459014843
    coal:
      datetime: '2020-01-01'
      source: 'IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1117.262766
    hydro:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=53
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: electricityMap, 2015 average
        value: 493.7680899731894
      - datetime: '2016-01-01'
        source: electricityMap, 2016 average
        value: 514.2989603956713
      - datetime: '2017-01-01'
        source: electricityMap, 2017 average
        value: 409.0929869387971
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 525.1871186670132
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 403.54356709907603
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 298.8199728907811
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 340.34978459014843
    nuclear:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=56
      value: 5.13
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 36.9
    wind:
      datetime: '2020-01-01'
      source: UNECE, https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37
        and WindEurope https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTA4LTEyVDA5OjU4OjM0LjA1MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--525dde85c30687b0af70bd8888f736cbb4bc11fd/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename*%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf#page=11
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: electricityMap, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.09559713993091913
        coal: 0.1741463540266478
        gas: 0.22443439919551225
        geothermal: 0.0
        hydro: 0.23046641926159206
        hydro discharge: 0.00022296442784058433
        nuclear: 0.07980127887337295
        oil: 0.00044697719209325736
        solar: 0.0002540485133358337
        unknown: 0.16423172814264578
        wind: 0.031070687325306556
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Riga
