bounding_box:
  - - 18.45
    - 41.87755
  - - 20.3398
    - 43.52384
capacity:
  coal: 210
  hydro: 649
  solar: 3
  wind: 118
contributors:
  - corradio
  - nessie2013
  - Pantkowsky
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 493.43182550062613
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 486.63240066748745
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 577.0218783956004
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 466.04717600583854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 410.4853027032386
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 407.6609032253837
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 353.9237999309435
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 493.43182550062613
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 486.63240066748745
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 577.0218783956004
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 466.04717600583854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 410.4853027032386
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 407.6609032253837
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 353.9237999309435
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 400.03933900187366
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 400.03933900187366
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0026941115602997627
        coal: 0.43558415171632503
        gas: 0.03602743879107918
        geothermal: 0.0005233025410668314
        hydro: 0.42848769194210234
        hydro discharge: 0.006422045793320414
        nuclear: 0.011082308684019646
        oil: 0.001874968190437762
        solar: 0.007329124523955026
        unknown: 0.01162240301241589
        wind: 0.05835189669206184
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Podgorica
