bounding_box:
  - - 20.46315
    - 40.8427269557
  - - 22.9523771502
    - 42.3202595078
capacity:
  coal: 824
  gas: 251
  hydro: 506
  nuclear: 0
  wind: 35
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 347.84516851012864
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 533.4220148709244
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 331.9709657483045
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 521.2259681477975
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 502.36946800227526
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 400.5841428003718
    hydro discharge:
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 347.84516851012864
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 533.4220148709244
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 331.9709657483045
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 521.2259681477975
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 502.36946800227526
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 400.5841428003718
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 477.10041160023616
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 477.10041160023616
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0016250415645462934
        coal: 0.4982395415491369
        gas: 0.06126927500077047
        geothermal: 0.00012594098077730974
        hydro: 0.29721891742401996
        hydro discharge: 0.002998142774419272
        nuclear: 0.08463328959256201
        oil: 2.6270415288616102e-05
        solar: 0.014344263119392842
        unknown: 0.000786094652001343
        wind: 0.038732684412767976
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Skopje
