bounding_box:
  - - -61.252194
    - 14.364404
  - - -60.732382
    - 14.888562
capacity:
  biomass: 15.082
  gas: 129
  geothermal: 0
  hydro: 0
  oil: 292
  solar: 53.97
  wind: 1.1
contributors:
  - PETILLON-Sebastien
parsers:
  price: FR_O.fetch_price
  production: FR_O.fetch_production
timezone: Europe/Paris
