bounding_box:
  - - -117.12776
    - 14.5388286402
  - - -86.811982388
    - 32.72083
capacity: {}
contributors:
  - scriptator
parsers:
  production: CENACE.fetch_production
subZoneNames:
  - MX-BC
  - MX-BCS
  - MX-CE
  - MX-NE
  - MX-NO
  - MX-NW
  - MX-OC
  - MX-OR
  - MX-PN
timezone: America/Mexico_City
