bounding_box:
  - - -117.12776
    - 14.5388286402
  - - -86.811982388
    - 32.72083
capacity: {}
contributors:
  - scriptator
parsers:
  production: CENACE.fetch_production
emissionFactors:
  direct:
    unknown:
      - datetime: '2020-01-01'
        source: 'IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and 2020, IEA, Paris'
        comment: 'Assumes a mix of 3.6% nuclear, 8.8% hydro, 8.4% oil, 63.4% gas, 4.2% coal, 4.3%solar, 5.9% wind, 1.5% other renewables with default IPCC2014 values.'
        value: 305
  lifecycle:
    unknown:
      - datetime: '2020-01-01'
        source: 'IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and 2020, IEA, Paris'
        comment: 'Assumes a mix of 3.6% nuclear, 8.8% hydro, 8.4% oil, 63.4% gas, 4.2% coal, 4.3%solar, 5.9% wind, 1.5% other renewables with default IPCC2014 values.'
        value: 411
subZoneNames:
  - MX-BC
  - MX-BCS
  - MX-CE
  - MX-NE
  - MX-NO
  - MX-NW
  - MX-OC
  - MX-OR
  - MX-PN
timezone: America/Mexico_City
sources:
  'IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and 2020, IEA, Paris':
    link: https://www.iea.org/data-and-statistics/charts/electricity-generation-mix-in-mexico-1-jan-30-sep-2019-and-2020
