bounding_box:
  - - 11.217621290000068
    - -29.45936818399987
  - - 25.759780721000112
    - -16.451057230999922
capacity:
  coal: 120
  hydro: 347
  oil: 38
  solar: 116
  wind: 5
contributors:
  - systemcatch
  - jarek
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 405.96637202354316
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 368.8456672172453
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 405.96637202354316
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 368.8456672172453
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 449.91762729828474
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 411.98310541931716
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 449.91762729828474
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 411.98310541931716
timezone: null
