bounding_box:
  - - 4.570648634000037
    - 57.49315013200005
  - - 11.014170769000089
    - 60.73048157269916
capacity:
  biomass: 22.3
  coal: 0
  gas: 35.8
  geothermal: 0
  hydro: 11498
  hydro storage: 892
  nuclear: 0
  oil: 0
  solar: 46.1
  unknown: 14
  wind: 1427
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 6.865837353449444
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 8.107995200490336
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.065085791416813
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 16.73031427246281
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 20.372847236224366
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 9.142464213867534
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 30.615743921131017
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 6.865837353449444
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 8.107995200490336
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.065085791416813
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 16.73031427246281
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 20.372847236224366
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 9.142464213867534
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 30.615743921131017
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 37.56687318716507
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; IPCC 2014
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 37.56687318716507
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005840177190292223
        coal: 0.007944803128926727
        gas: 0.006495088069049102
        geothermal: 1.0181605819504837e-05
        hydro: 0.806496945797897
        hydro discharge: 0.0677005442260501
        nuclear: 0.00600493897332054
        oil: 0.00032219318886949846
        solar: 0.004387040092673053
        unknown: 0.000739163481253074
        wind: 0.09405895574406402
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: null
