bounding_box:
  - - 4.143809441000116
    - 60.43027545054864
  - - 14.661440063000043
    - 65.490423895
capacity:
  biomass: 17.7
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 4845
  hydro storage: 87
  nuclear: 0
  oil: 0
  solar: 21.9
  unknown: 46.8
  wind: 2112
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 16.644207302874474
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 16.593698989188432
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.34131121195846
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 21.04457168433364
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 14.667641397306
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 13.145697349281024
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 13.43629439767019
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 16.644207302874474
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 16.593698989188432
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.34131121195846
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 21.04457168433364
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 14.667641397306
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 13.145697349281024
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 13.43629439767019
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 25.551506346718046
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; IPCC 2014
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 25.551506346718046
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0008927043647983744
        coal: 5.222730585202593e-05
        gas: 0.0004177922878590006
        geothermal: 2.8433649138013986e-08
        hydro: 0.7998066784063416
        hydro discharge: 0.02523665227607586
        nuclear: 0.0020635561633478476
        oil: 2.041156892787564e-06
        solar: 3.192037275297818e-05
        unknown: 0.006718923988342442
        wind: 0.1647787141929597
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: null
