bounding_box:
  - - 7.610326512408815
    - 58.38472727500012
  - - 13.388184448000061
    - 63.128901615737796
capacity:
  biomass: 46
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 3754
  hydro storage: 1
  nuclear: 0
  oil: 0
  solar: 78.9
  unknown: 0
  wind: 385
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 7.85495144586737
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 8.367211519837456
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.201344138211498
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 13.574603019478106
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 15.844279128932419
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 10.984900016092158
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 18.03075364405762
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 7.85495144586737
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 8.367211519837456
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 10.201344138211498
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 13.574603019478106
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 15.844279128932419
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 10.984900016092158
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 18.03075364405762
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 31.12659599726026
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; IPCC 2014
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 31.12659599726026
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.003363200206807748
        coal: 0.002479283457788603
        gas: 0.007693122000113427
        geothermal: 3.0191171424283125e-06
        hydro: 0.8692334556644264
        hydro discharge: 0.03262250974789261
        nuclear: 0.027940510889597286
        oil: 9.289779048470409e-05
        solar: 0.0012456863455039995
        unknown: 0.00528475643853245
        wind: 0.05004185581354628
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: null
