bounding_box:
  - - 11.018809441000087
    - 63.879640651798496
  - - 31.576996290000153
    - 71.6652692730001
capacity:
  biomass: 0.3
  coal: 0
  gas: 248
  geothermal: 0
  hydro: 5288
  hydro storage: 2
  nuclear: 0
  oil: 0
  solar: 1.6
  unknown: 39.3
  wind: 1132
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.1564575503542
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 28.430619700670714
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 24.324130622568624
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 27.25884252643962
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 27.533138350488123
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 21.090061839016926
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 6.628141281423535
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.1564575503542
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 28.430619700670714
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 24.324130622568624
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 27.25884252643962
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 27.533138350488123
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 21.090061839016926
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 6.628141281423535
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 29.82377936407315
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; IPCC 2014
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 29.82377936407315
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00010677513331664778
        coal: 0.0001347549487223612
        gas: 0.0008908431697485417
        geothermal: 0.0
        hydro: 0.8970656712173826
        hydro discharge: 3.4241863554133874e-05
        nuclear: 0.00649460464333893
        oil: 2.9348047470663005e-06
        solar: 2.227513621088287e-05
        unknown: 0.01162225529896723
        wind: 0.08363015258595581
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: null
