capacity:
  biomass: 113.3
  coal: 0
  gas: 473.4
  geothermal: 0
  hydro: 33625
  hydro storage: 1438
  nuclear: 0
  oil: 0
  solar: 160
  unknown: 112.6
  wind: 5056
contributors:
  - corradio
emissionFactors:
  lifecycle:
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
subZoneNames:
  - NO-NO1
  - NO-NO2
  - NO-NO3
  - NO-NO4
  - NO-NO5
timezone: Europe/Oslo
