capacity:
  biomass: 113.3
  coal: 0
  gas: 473.4
  geothermal: 0
  hydro: 33625
  hydro storage: 1438
  nuclear: 0
  oil: 0
  solar: 160
  unknown: 112.6
  wind: 5056
contributors:
  - corradio
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 32.51061695202239
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      datetime: '2012-01-01'
      source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation."; IPCC 2014
      value: 883.79433
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 32.51061695202239
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.003370000115291126
        coal: 0.00297301580330705
        gas: 0.007069411944029302
        geothermal: 3.7720935553373134e-06
        hydro: 0.8447082089673605
        hydro discharge: 0.04089857883901085
        nuclear: 0.010382064895908389
        oil: 0.00011865184164168842
        solar: 0.0016135108065831775
        unknown: 0.004522524222705108
        wind: 0.08434138148245467
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
subZoneNames:
  - NO-NO1
  - NO-NO2
  - NO-NO3
  - NO-NO4
  - NO-NO5
timezone: Europe/Oslo
