bounding_box:
  - - 119.31099810998111
    - 4.57480853775256
  - - 127.08266582665826
    - 10.957111072508837
capacity:
  battery storage: 35
  biomass: 326
  coal: 1412
  gas: 1
  hydro: 36
  oil: 644
  solar: 487
  wind: 90
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
parsers:
  production: PH.fetch_production
timezone: Asia/Manila
