bounding_box:
  - - -17.752105272999927
    - 29.529242255000057
  - - -15.354969855999883
    - 33.61078522300012
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1057.262766
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 372.109361
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
  lifecycle:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 439.145806
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1099.976527
    gas:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 492.109361
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      datetime: '2021-01-01'
      source: IPCC 2014; EU-ETS, ENTSO-E 2021
      value: 1124.903938
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
flag_file_name: pt.png
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: null
