bounding_box:
  - - 50.250987175000034
    - 24.059871521000062
  - - 52.11654707100007
    - 26.660101630000042
capacity: #
  biomass:
    - datetime: '2016-01-01'
      source: "IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing"
      value: 19
    - datetime: '2021-01-01'
      source: "IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing"
      value: 19
  gas:
    - datetime: '2016-01-01'
      source: IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing
      value: 8559
    - datetime: '2021-01-01'
      source: IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing
      value: 10576
  solar:
    - datetime: '2016-01-01'
      source: IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing
      value: 5.1
    - datetime: '2021-01-01'
      source: IRENA, https://docs.google.com/spreadsheets/d/1ownS3qse6zDG4gNnKEZDroIKLNiqZcULqp34LJUxrL0/edit?usp=sharing
      value: 5.1
contributors:
  - q--
  - nessie2013
parsers:
  consumption: GCCIA.fetch_consumption
timezone: Asia/Qatar
