bounding_box:
  - - 54.374008
    - -22.069087
  - - 56.33463
    - -20.421464
capacity:
  biomass: 215
  coal: 211
  gas: 80
  hydro: 138
  oil: 221
  solar: 189
  wind: 15
contributors:
  - PETILLON-Sebastien
  - VIKTORVAV99
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 357.6061183151501
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 425.62923233408634
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 399.6759026824
    hydro discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 357.6061183151501
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 425.62923233408634
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 399.6759026824
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 532.0876068276795
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 532.0876068276795
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07849569235374991
        coal: 0.3188451703582329
        gas: 0.0467158862871482
        geothermal: 0.0
        hydro: 0.13402730812991306
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.3430428697495389
        solar: 0.07727385593837005
        unknown: 0.0
        wind: 0.001596552926444654
parsers:
  production: FR_O.fetch_production
timezone: Indian/Reunion
