bounding_box:
  - - 18.82982
    - 42.2452243971
  - - 22.9860185076
    - 46.1717298447
capacity:
  biomass: 2
  coal: 5661
  gas: 486
  hydro: 2491
  hydro storage: 642
  solar: 3
  unknown: 35
  wind: 397
contributors:
  - corradio
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 514.4111478780175
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 488.55287466343674
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 504.33468856491385
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 517.4264340785641
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 468.4314815771853
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 514.4111478780175
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 488.55287466343674
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 504.33468856491385
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 517.4264340785641
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 468.4314815771853
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 537.200044744147
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 537.200044744147
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 29.7
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.006789618762757285
        coal: 0.5841566724942064
        gas: 0.015734866536458877
        geothermal: 1.4234641723441736e-05
        hydro: 0.30120146083215404
        hydro discharge: 0.017881646258618968
        nuclear: 0.03817331776213811
        oil: 9.145967575073363e-05
        solar: 0.003907631079257372
        unknown: 0.02310263670499563
        wind: 0.008948209565148505
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
timezone: Europe/Belgrade
