bounding_box:
  - - 26.444509311000104
    - 40.69268056200022
  - - 86.53054243358639
    - 80.6748721370002
capacity:
  hydro: 19500
  nuclear: 27914
  unknown: 125014
contributors:
  - denplis
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 389.41640931667854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 386.8323672175498
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.7866206569542
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 390.952316008629
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 389.41640931667854
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 386.8323672175498
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.7866206569542
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 390.952316008629
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 356.94578769497673
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 356.94578769497673
    unknown:
      _comment: 'Assumes weighted average emission factor based on estimated 2021
        fuel consumption: 6.7% * 820 g/kWh (coal) + 0.5% * 650 g/kWh (oil) + 89.0%
        * 490 g/kWh (gas) + 3.8% * 700 g/kWh (other)= 517 g/kWh, Source: https://minenergo.gov.ru/node/11323
        2018-06-26 Table 7.3., p.80, Sum of zones Northwest, Central, Volga, South,
        Ural'
      source: assumes 89% gas, 7% coal, <1% oil, 4% other
      value: 517
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00016269593779307253
        coal: 0.002591019926478765
        gas: 0.0011745698317258079
        geothermal: 2.797296406795891e-07
        hydro: 0.06782930258072419
        hydro discharge: 1.3837531947977257e-06
        nuclear: 0.2505284119748738
        oil: 6.883722478060441e-05
        solar: 0.0018235418395603495
        unknown: 0.6756927607121264
        wind: 0.000262088192472771
flag_file_name: ru.png
parsers:
  production: RU.fetch_production
timezone: Europe/Moscow
