bounding_box:
  - - 69.88395226418567
    - 48.571011048000116
  - - 122.63913943863423
    - 81.78880442900012
capacity:
  hydro: 25286
  unknown: 26570
contributors:
  - denplis
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.01740080595744
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.7933394725147
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 356.0279249226042
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 325.8976606822384
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.01740080595744
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.7933394725147
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 356.0279249226042
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 325.8976606822384
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 368.2988164796275
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 414.67967187303975
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 493.7909799131237
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 453.45101844835244
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 368.2988164796275
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 414.67967187303975
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 493.7909799131237
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 453.45101844835244
    unknown:
      _comment: 'Assumes weighted average emission factor based on estimated 2021
        fuel consumption: 86.0% * 820 g/kWh (coal) + 0.3% * 650 g/kWh (oil) + 9.1%
        * 490 g/kWh (gas) + 4.7% * 700 g/kWh (other)= 784 g/kWh, Source: https://minenergo.gov.ru/node/11323
        2018-06-26 Table 7.3., p.80, Siberian zone'
      source: assumes 86% coal, 9% gas, <1% oil, 5% other
      value: 784
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.294049358262306e-05
        coal: 0.004143078389017562
        gas: 0.0011987748486757908
        geothermal: 2.2198579466046784e-06
        hydro: 0.4319238891921842
        hydro discharge: 9.164270902774583e-10
        nuclear: 0.0006696673863185435
        oil: 6.270024442957947e-05
        solar: 0.0014655094047953219
        unknown: 0.5604868171706635
        wind: 5.93185266412234e-05
flag_file_name: ru.png
parsers:
  production: RU.fetch_production
timezone: Europe/Moscow
