bounding_box:
  - - 69.88395226418567
    - 48.571011048000116
  - - 122.63913943863423
    - 81.78880442900012
capacity:
  hydro: 25286
  unknown: 26570
contributors:
  - denplis
  - systemcatch
  - alixunderplatz
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.01740080595744
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.7933394725147
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 356.0279249226042
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 325.8976606822384
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.01740080595744
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 296.7933394725147
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 356.0279249226042
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 325.8976606822384
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 453.4506704652607
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 453.4506704652607
    unknown:
      _comment: 'Assumes weighted average emission factor based on estimated 2021
        fuel consumption: 86.0% * 820 g/kWh (coal) + 0.3% * 650 g/kWh (oil) + 9.1%
        * 490 g/kWh (gas) + 4.7% * 700 g/kWh (other)= 784 g/kWh, Source: https://minenergo.gov.ru/node/11323
        2018-06-26 Table 7.3., p.80, Siberian zone'
      source: assumes 86% coal, 9% gas, <1% oil, 5% other
      value: 784
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.2941410009713337e-05
        coal: 0.00414308086676488
        gas: 0.0011987754596271842
        geothermal: 2.2198579466046784e-06
        hydro: 0.431923864278944
        hydro discharge: 9.164270902774583e-10
        nuclear: 0.0006696813363753621
        oil: 6.270031231306764e-05
        solar: 0.0014655092690283454
        unknown: 0.5604868211079058
        wind: 5.932259965051352e-05
flag_file_name: ru.png
parsers:
  production: RU.fetch_production
timezone: Europe/Moscow
