bounding_box:
  - - 10.608164910000113
    - 56.392035223000065
  - - 19.8385522800001
    - 62.67478628775066
capacity:
  biomass: 2561
  coal: 0
  gas: 950
  geothermal: 0
  hydro: 2593
  nuclear: 6882
  oil: 243
  solar: 1109
  wind: 3000
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 133.9240359
    coal:
      datetime: '2020-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1057.262766
    gas:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 447.9740216
    oil:
      datetime: '2021-01-01'
      source: 'EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 880.903938
  lifecycle:
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        EU-ETS, ENTSO-E: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link'
      value: 1153.629975
    unknown:
      - _comment: Uses the 2020 (2022 edition) eurostat production values for SE for
          the sources in unknown
        _url: https://ec.europa.eu/eurostat/documents/38154/4956218/Energy-Balances-January-2022-edition.zip/2dc71f1b-806a-b9ed-e77d-67b7c705197b?t=1643660477829
        datetime: '2020-01-01'
        source: assumes 98.26 % biomass, 1.09% oil based thermal, 0.64% peat, 0.01%
          coal
        value: 238.4
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
  productionPerUnit: ENTSOE.fetch_production_per_units
timezone: Europe/Stockholm
