bounding_box:
  - - 103.14039147200003
    - 0.7643089860000885
  - - 104.50342858200003
    - 1.9486351580000445
capacity:
  biomass: 256.8
  coal: 763.6
  gas: 10671
  geothermal: 0
  oil: 0
  solar: 486.9
contributors:
  - corradio
  - jarek
  - r24mille
  - systemcatch
  - alixunderplatz
  - q--
  - nessie2013
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.93472299872286
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 373.4849167376516
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 372.9033513236525
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 372.16040720903
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.93472299872286
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 373.4849167376516
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 372.9033513236525
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 372.16040720903
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 491.319745388494
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 491.319745388494
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.0989757147822616e-07
        coal: 0.0005229464985545066
        gas: 0.9717309828819485
        geothermal: 0.0
        hydro: 8.242536925793498e-05
        hydro discharge: 0.0
        nuclear: 2.6776123416227276e-05
        oil: 0.0
        solar: 0.006996661565346144
        unknown: 0.02059445128771734
        wind: 2.6791457961084702e-05
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  price: SG.fetch_price
  production: SG.fetch_production
timezone: Asia/Singapore
