bounding_box:
  - - 96.85140100100011
    - 5.129890035000059
  - - 106.15099776200003
    - 20.94500640900013
capacity:
  battery storage: 0
  biomass: 4533.6
  coal: 6641.06
  gas: 33098.85
  geothermal: 0.3
  hydro: 7573.17
  hydro storage: 1000
  nuclear: 0
  oil: 1501.1
  solar: 3040.17
  unknown: 0
  wind: 1539.21
contributors:
  - PPsyrius
emissionFactors:
  lifecycle:
    unknown:
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '1998-01-01'
        source: EPPO 1998
        value: 636
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '1999-01-01'
        source: EPPO 1999
        value: 646
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2000-01-01'
        source: EPPO 2000
        value: 634
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2001-01-01'
        source: EPPO 2001
        value: 604
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2002-01-01'
        source: EPPO 2002
        value: 587
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2003-01-01'
        source: EPPO 2003
        value: 573
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2004-01-01'
        source: EPPO 2004
        value: 581
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2005-01-01'
        source: EPPO 2005
        value: 571
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2006-01-01'
        source: EPPO 2006
        value: 571
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2007-01-01'
        source: EPPO 2007
        value: 571
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2008-01-01'
        source: EPPO 2008
        value: 570
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2009-01-01'
        source: EPPO 2009
        value: 560
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2010-01-01'
        source: EPPO 2010
        value: 551
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2011-01-01'
        source: EPPO 2011
        value: 530
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2012-01-01'
        source: EPPO 2012
        value: 530
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2013-01-01'
        source: EPPO 2013
        value: 532
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2014-01-01'
        source: EPPO 2014
        value: 532
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2015-01-01'
        source: EPPO 2015
        value: 507
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2016-01-01'
        source: EPPO 2016
        value: 493
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2017-01-01'
        source: EPPO 2017
        value: 471
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2018-01-01'
        source: EPPO 2018
        value: 459
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2019-01-01'
        source: EPPO 2019
        value: 445
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2020-01-01'
        source: EPPO 2020
        value: 442
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2021-01-01'
        source: EPPO 2021
        value: 433
      - _comment: Gross Energy Generation of EGAT and Net Energy Generation of IPP, SPP, and VSPP
        datetime: '2022-01-01'
        source: EPPO 2022
        value: 409
fallbackZoneMixes:
  _source: IEA 2020 (used because Our World in Data has a lot of 'other renewables'
    generation not broken down by type). Biomass includes waste.
  _url: https://www.iea.org/data-and-statistics/data-browser?country=THAILAND&fuel=Energy%20supply&indicator=ElecGenByFuel
  powerOriginRatios:
    value:
      biomass: 0.0912401506077485
      coal: 0.193458983021716
      gas: 0.646700218606825
      geothermal: 5.371175052e-06
      hydro: 0.0248631693155512
      oil: 0.0007036239318076
      solar: 0.026469150656089
      wind: 0.0165593326852115
isLowCarbon:
  unknown:
    _comment: Sum of renewable sources in TH unknown production
    value: 0.159
isRenewable:
  unknown:
    _comment: Sum of renewable sources in TH unknown production
    value: 0.159
parsers:
  consumption: TH.fetch_consumption
  price: TH.fetch_price
  production: TH.fetch_production
  productionPerModeForecast: TH.fetch_generation_forecast
timezone: Asia/Bangkok
