_comment: https://doi.org/10.1016/j.rser.2017.01.060 says pumped hydro not economically
  viable. http://www.hurriyetdailynews.com/turkey-plans-to-hold-new-big-tenders-for-wind-solar-plants-by-summer-2018-minister-127769
  says battery will be tendered summer 2018 so below battery storage will need to
  be updated when built.
bounding_box:
  - - 25.16325931100002
    - 35.319778545000034
  - - 45.30699282900011
    - 42.598781643000095
capacity:
  battery storage: 0
  biomass: 1711
  coal: 20037
  gas: 25456.8
  geothermal: 1676
  hydro: 31507.9
  hydro storage: 0
  oil: 251.9
  solar: 8028.9
  unknown: 801.6
  wind: 10861.5
contributors:
  - corradio
  - olivierSemet
  - lorrieq
  - nessie2013
  - lgrigoryeva1
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 391.9231166685683
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 406.09210216862743
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 367.8879660293103
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 363.11298731762804
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 362.32319395730116
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 391.9231166685683
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 406.09210216862743
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 367.8879660293103
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 363.11298731762804
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 362.32319395730116
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 432.7545048821836
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 432.7545048821836
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.15
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.016662403535200147
        coal: 0.3177122279562548
        gas: 0.32604649401224345
        geothermal: 0.030641324295390803
        hydro: 0.17150499914943163
        hydro discharge: 4.262290936250711e-06
        nuclear: 0.0010907335498947662
        oil: 0.0011891551898668168
        solar: 0.04104178979446196
        unknown: 0.0001991605200486841
        wind: 0.09391491543605061
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: TR.fetch_price
  production: TR.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
timezone: Europe/Istanbul
