bounding_box:
  - - -179.64350338399993
    - 50.71539948100022
  - - 180.28093509200022
    - 71.91250234600014
emissionFactors:
  direct:
    coal:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1054.589992
    gas:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 470.7986093
    oil:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 713.1828107
  lifecycle:
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1061.619377
flag_file_name: us.png
timezone: null
