bounding_box:
  - - -107.926457081158
    - 30.3593306971005
  - - -89.4563897448683
    - 49.5000212518403
capacity:
  battery storage: 27.9
  biomass: 344.2
  coal: 22064.3
  gas: 36281.3
  geothermal: 0
  hydro: 3104.1
  hydro storage: 259.2
  nuclear: 2068.7
  oil: 2185.4
  solar: 409.8
  unknown: 62
  wind: 29163.9
comment: Southwest Power Pool
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 425.73362077872713
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 410.3856106309873
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 360.08901526042365
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 336.2123050804945
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 346.3017284560946
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1014.625275
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 459.1389525
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 425.73362077872713
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 410.3856106309873
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 360.08901526042365
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 336.2123050804945
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 346.3017284560946
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 975.0111176
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 495.53661158608855
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 66.69147532
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1044.656633
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 579.1389525
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 495.53661158608855
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1219.0111176
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.66
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0003230959316681301
        coal: 0.3559401411640917
        gas: 0.19980546847493288
        geothermal: 1.1609436623585774e-06
        hydro: 0.04247915147225188
        hydro discharge: 6.463577817368144e-08
        nuclear: 0.05769610564137265
        oil: 0.00051958955564343
        solar: 0.002218205602872569
        unknown: 0.0028117001625664454
        wind: 0.3382034220121531
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: US_SPP.fetch_load_forecast
  production: US_SPP.fetch_production
  productionPerModeForecast: US_SPP.fetch_wind_solar_forecasts
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Central
