bounding_box:
  - - -81.37844
    - 32.6102500000001
  - - -75.53103
    - 37.04465
capacity:
  battery storage: 0
  biomass: 409.1
  coal: 3321.4
  gas: 6489.8
  geothermal: 0
  hydro: 228
  hydro storage: 0
  nuclear: 3722.7
  oil: 282.1
  solar: 1749.1
  unknown: 54
  wind: 0
comment: Duke Energy Progress East
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 268.1840240341385
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 265.5578662969244
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 237.11251498252247
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 237.68880592797754
    biomass:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 216.6227355
    coal:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 937.9666611
    gas:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 394.223375
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 268.1840240341385
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 265.5578662969244
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 237.11251498252247
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 237.68880592797754
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 331.97896099655054
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 324.7871979417284
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 293.6595248219585
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 292.6464775651042
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1059.9982231
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 331.97896099655054
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 324.7871979417284
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 293.6595248219585
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 292.6464775651042
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 25.6
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
timezone: US/Eastern
