bounding_box:
  - - -124.909721
    - 32.0341570000001
  - - -113.631212
    - 41.965851
capacity:
  battery storage: 2283.9
  biomass: 1179.8
  coal: 62.5
  gas: 33077
  geothermal: 2103.5
  hydro: 6705.6
  hydro storage: 2094.4
  nuclear: 2323
  oil: 391.5
  solar: 15842.4
  unknown: 99.7
  wind: 6140.2
comment: California Independent System Operator
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 192.92888036826204
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 181.4752170014332
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 253.85060517261823
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 235.04724861550912
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 514.4743088
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 403.8432591
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 95.82104392
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 192.92888036826204
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 181.4752170014332
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 253.85060517261823
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 235.04724861550912
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 910.2232446
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 251.31712032739068
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 101.6370901
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 587.8020898
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 523.8432591000001
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 133.82104392
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 251.31712032739068
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1154.2232446
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0033380227916333374
        biomass: 0.019058202777675472
        coal: 0.0301996080246905
        gas: 0.4215193050890347
        geothermal: 0.033741227420655336
        hydro: 0.11268979813931479
        hydro discharge: 0.00011561446433630052
        nuclear: 0.11320006920756431
        oil: 0.000541923583058686
        solar: 0.15825656177245656
        unknown: 0.014146646578320266
        wind: 0.09391255875402638
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: US_CA.fetch_production
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
