bounding_box:
  - - -116.925459495
    - 32.118592
  - - -113.962511
    - 34.535375
capacity:
  battery storage: 30
  biomass: 94.6
  coal: 0
  gas: 605.5
  geothermal: 791.4
  hydro: 83.9
  hydro storage: 0
  nuclear: 0
  oil: 24.9
  solar: 386.4
  unknown: 0
  wind: 0
comment: Imperial Irrigation District
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 470.4948401559973
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 477.5906091949696
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 476.3870350461926
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 472.4009481555156
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 471.3724863
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 56.8894463
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 470.4948401559973
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 477.5906091949696
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 476.3870350461926
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 472.4009481555156
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 605.7101776743226
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 39.38869109
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 591.3724863
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 94.8894463
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 605.7101776743226
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.00014984215578368572
        biomass: 0.000225729553931566
        coal: 0.005550543550678585
        gas: 0.23291767987399611
        geothermal: 0.0003752716324453547
        hydro: 0.05083597597810008
        hydro discharge: 5.051300709932807e-06
        nuclear: 0.004247182935320131
        oil: 1.285688207570592e-05
        solar: 0.04570280061401524
        unknown: 0.6568874556626902
        wind: 0.003218839565473824
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
