bounding_box:
  - - -83.14555
    - 31.584470000000103
  - - -78.92575821
    - 35.2360579840001
capacity:
  battery storage: 4
  biomass: 229.6
  coal: 1431.5
  gas: 3511.2
  geothermal: 0
  hydro: 254.9
  hydro storage: 587.2
  nuclear: 1029.6
  oil: 33.8
  solar: 903.2
  unknown: 0
  wind: 0
comment: South Carolina Electric & Gas Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 415.9966831424999
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 347.8776522729067
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 309.5380666314754
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 324.31032673234637
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 849.2213607
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 407.4177138
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 415.9966831424999
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 347.8776522729067
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 309.5380666314754
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 324.31032673234637
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 441.1224874951236
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 90.54773858
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 932.0702837
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 527.4177138
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 441.1224874951236
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.1747773500179321
        gas: 0.5139316180625058
        geothermal: 0.0
        hydro: 0.0344832247154446
        hydro discharge: 0.0002479312888699973
        nuclear: 0.20325301791199152
        oil: 5.835318396970806e-06
        solar: 0.07064558608613784
        unknown: 0.002588342445884597
        wind: 6.808856794717761e-05
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
