bounding_box:
  - - -82.8222040759999
    - 31.5821888830001
  - - -78.04086
    - 35.334748543
capacity:
  battery storage: 0
  biomass: 219.5
  coal: 3650.1
  gas: 1102
  geothermal: 0
  hydro: 231.2
  hydro storage: 0
  nuclear: 0
  oil: 229.4
  solar: 98.2
  unknown: 0
  wind: 0
comment: South Carolina Public Service Authority
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 494.1308716954582
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 430.6769160520071
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 411.06058697926824
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 446.1247623700005
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1072.534134
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 442.9124649
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 494.1308716954582
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 430.6769160520071
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 411.06058697926824
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 446.1247623700005
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 648.4341212169911
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 53.68073353
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1165.692392
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 562.9124649
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 648.4341212169911
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.6125624480985956e-07
        coal: 0.3957301868227805
        gas: 0.3280042565398146
        geothermal: 0.0
        hydro: 0.045623046667090286
        hydro discharge: 0.00012504055046487665
        nuclear: 0.1781279217049388
        oil: 6.433159053536302e-05
        solar: 0.025884925422977215
        unknown: 0.026264676829403106
        wind: 0.00017610253156315076
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
