bounding_box:
  - - -124.123781
    - 37.076039301
  - - -120.084803325
    - 41.868139
capacity:
  battery storage: 0
  biomass: 9
  coal: 0
  gas: 1934.8
  geothermal: 0
  hydro: 740.3
  hydro storage: 0
  nuclear: 0
  oil: 72.2
  solar: 326.1
  unknown: 0
  wind: 0
comment: Balancing Authority Of Northern California
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 213.00632513718543
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 152.35947576490497
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 165.61323771933735
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 194.3736474753835
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 389.6341439
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 213.00632513718543
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 152.35947576490497
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 165.61323771933735
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 194.3736474753835
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 276.85737019433964
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 509.6341439
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 276.85737019433964
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 1.8189229966031377e-06
        biomass: 0.0008732453922226963
        coal: 0.014788161951999411
        gas: 0.35721924407094224
        geothermal: 0.0007687846837166392
        hydro: 0.5311137505120095
        hydro discharge: 8.350026621833115e-06
        nuclear: 0.029478826496272006
        oil: 0.00045178374679494596
        solar: 0.03195876144948064
        unknown: 0.011756279882031453
        wind: 0.02255330545866965
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
