bounding_box:
  - - -84.82173
    - 33.03163
  - - -77.75453
    - 37.0883200000001
capacity:
  battery storage: 0
  biomass: 90.9
  coal: 7045.1
  gas: 10719
  geothermal: 0
  hydro: 1180.7
  hydro storage: 2166
  nuclear: 7517.5
  oil: 143.4
  solar: 2252.8
  unknown: 0
  wind: 0
comment: Duke Energy Carolinas
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 243.19680986398103
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 237.18767739206723
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 213.5382493437822
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 234.16589637442436
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 856.3493858
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 396.0379906
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 243.19680986398103
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 237.18767739206723
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 213.5382493437822
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 234.16589637442436
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 291.1061293572224
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 281.72644880766484
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.9364160535594
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 278.99298581150015
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 941.3628778000001
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 516.0379906000001
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 291.1061293572224
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 281.72644880766484
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.9364160535594
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 278.99298581150015
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.53333333
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.7605106047295474e-05
        coal: 0.18196863906930855
        gas: 0.2549783473720139
        geothermal: 6.573910461342155e-06
        hydro: 0.05254230367792003
        hydro discharge: 0.025748431883591848
        nuclear: 0.47422189553580113
        oil: 9.241768773546968e-05
        solar: 0.006750023739973227
        unknown: 0.0034720982202961805
        wind: 0.0001845655953013872
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 5.75879223961103e-05
        coal: 0.19319338234333655
        gas: 0.2164968644835529
        geothermal: 1.0084026046398e-05
        hydro: 0.04862600555969037
        hydro discharge: 0.025040091586863673
        nuclear: 0.5026198905445081
        oil: 0.0001276132165919133
        solar: 0.010017096014050885
        unknown: 0.0035406646543163943
        wind: 0.0002744359916115254
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
