bounding_box:
  - - -83.214478374
    - 26.985591
  - - -81.1327000919999
    - 28.9295718550001
capacity:
  battery storage: 0
  biomass: 71.6
  coal: 678.9
  gas: 5535.7
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 133.4
  solar: 895.3
  unknown: 335.3
  wind: 0
comment: Tampa Electric Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 475.0236389891161
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 444.14528014674994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 430.721133184305
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.9654415326255
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 432.8237021
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 475.0236389891161
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 444.14528014674994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 430.721133184305
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.9654415326255
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 581.4050153288631
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 551.5083650873985
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 538.4892905752055
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 544.6556981438661
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1248.927719
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 866.085401
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 552.8237021
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 581.4050153288631
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 551.5083650873985
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 538.4892905752055
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 544.6556981438661
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 9.347549434491602e-06
        coal: 0.22012066217194703
        gas: 0.6541426885690353
        geothermal: 1.6403193644155511e-06
        hydro: 0.00019235059162423936
        hydro discharge: 6.550796183768177e-08
        nuclear: 0.003712178978233014
        oil: 2.691329104139317e-05
        solar: 0.007527595010564251
        unknown: 0.1142401548084154
        wind: 2.573240084933256e-05
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
