bounding_box:
  - - -85.65399
    - 25.7184577510001
  - - -80.123257233
    - 31.2115600000001
capacity:
  battery storage: 0
  biomass: 1.6
  coal: 1429.2
  gas: 853.3
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Seminole Electric Cooperative
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 370.0559152858642
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 380.9668522198512
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 426.3766914568056
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 576.2028045156524
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 964.3118179
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 386.3298038
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 370.0559152858642
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 380.9668522198512
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 426.3766914568056
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 576.2028045156524
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 803.9654161855685
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1062.1123579
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 506.3298038
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 803.9654161855685
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5427336130368051
        gas: 0.44546419186580155
        geothermal: 0.0
        hydro: 1.781978997487099e-05
        hydro discharge: 0.0
        nuclear: 0.0015195039733866462
        oil: 7.561663413271827e-06
        solar: 0.008247981961196492
        unknown: 0.0024785122972310314
        wind: 4.337474233234317e-08
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
