bounding_box:
  - - -83.03593
    - 24.044093
  - - -79.53074
    - 30.69435
capacity:
  battery storage: 0
  biomass: 0
  coal: 929
  gas: 3119.3
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 95.8
  solar: 166.9
  unknown: 0
  wind: 0
comment: Florida Municipal Power Pool
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 477.2192753178431
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 462.3785463463708
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 441.0877526137168
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 440.5330707389499
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 768.4856555
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 446.015972
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 477.2192753178431
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 462.3785463463708
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 441.0877526137168
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 440.5330707389499
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 582.5695563225543
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 828.4856555
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 566.0159719999999
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 582.5695563225543
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.26201719773230453
        gas: 0.613033947173487
        geothermal: 0.0
        hydro: 0.0001394130045011424
        hydro discharge: 5.832884969865417e-07
        nuclear: 0.06853034630299272
        oil: 0.0002193495730979315
        solar: 0.02697457806266613
        unknown: 0.029083877862535776
        wind: 3.190452430028712e-07
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
