bounding_box:
  - - -86.0998
    - 29.463185332
  - - -80.848769105
    - 31.50107
capacity:
  battery storage: 5
  biomass: 148.5
  coal: 595
  gas: 2166.9
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 248.4
  solar: 35.1
  unknown: 0
  wind: 0
comment: Jea
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 476.645720236363
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 464.5018120080076
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 503.5466950538667
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.0989427486165
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 612.0220147
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 476.645720236363
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 464.5018120080076
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 503.5466950538667
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.0989427486165
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 680.8678239691804
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 82.16971627
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 880.658933
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 732.0220147
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 680.8678239691804
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.2749311476664992
        gas: 0.6227577489480733
        geothermal: 0.0
        hydro: 0.00030326920332088124
        hydro discharge: 1.999030755215585e-06
        nuclear: 0.05672393654630737
        oil: 0.00022468390916646958
        solar: 0.016396516409914887
        unknown: 0.028658852309641405
        wind: 1.4039053924114114e-06
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
