bounding_box:
  - - -83.214478374
    - 26.985591
  - - -81.1327000919999
    - 28.9295718550001
capacity:
  battery storage: 0
  biomass: 71.6
  coal: 678.9
  gas: 5535.7
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 133.4
  solar: 895.3
  unknown: 335.3
  wind: 0
comment: Tampa Electric Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 475.0236389891161
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 444.14528014674994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 430.721133184305
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.9654415326255
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 432.8237021
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 475.0236389891161
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 444.14528014674994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 430.721133184305
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.9654415326255
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 593.9242899009478
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1248.927719
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 866.085401
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 552.8237021
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 593.9242899009478
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.15967465664036018
        gas: 0.6530324407357712
        geothermal: 0.0
        hydro: 0.0004560149242425607
        hydro discharge: 5.371675996342776e-07
        nuclear: 0.003200520707059573
        oil: 0.00013046108297898283
        solar: 0.051313070737822264
        unknown: 0.13219152367546516
        wind: 3.9725631194131884e-07
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
