bounding_box:
  - - -84.94623
    - 29.865082
  - - -83.591841
    - 31.123546
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 961.8
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 62
  unknown: 0
  wind: 0
comment: City Of Tallahassee
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 370.0914917267338
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 364.65887659525646
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 361.10200989810795
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 357.15150567890674
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 359.8683566
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 370.0914917267338
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 364.65887659525646
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 361.10200989810795
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 357.15150567890674
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 464.92643416809295
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 479.8683566
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 464.92643416809295
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.045252770889362345
        gas: 0.8630577797375806
        geothermal: 0.0
        hydro: 0.01146846221461586
        hydro discharge: 6.195935640855483e-05
        nuclear: 0.04525397514931368
        oil: 5.246353020618677e-06
        solar: 0.032492257809134624
        unknown: 0.002338858376119125
        wind: 6.751859872166533e-05
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
