bounding_box:
  - - -83.67149
    - 24.02126
  - - -79.53074
    - 31.33017
capacity:
  battery storage: 493
  biomass: 622.4
  coal: 0
  gas: 23743.6
  geothermal: 0
  hydro: 43.5
  hydro storage: 0
  nuclear: 3797.2
  oil: 261.5
  solar: 3542.6
  unknown: 0
  wind: 0
comment: Florida Power & Light Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 318.3170500545663
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 308.8861886828243
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 311.5020258130034
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 304.4464690231568
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 367.4893706
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 318.3170500545663
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 308.8861886828243
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 311.5020258130034
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 304.4464690231568
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 390.0504417
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 413.51071063760685
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 402.3689591805507
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 405.3154501494946
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 396.528547525379
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 902.3445824
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 487.4893706
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 413.51071063760685
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 402.3689591805507
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 405.3154501494946
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 396.528547525379
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 634.0504417
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 4.659351744906394e-05
        coal: 0.04772027697126437
        gas: 0.7086443909314392
        geothermal: 8.20007897596486e-06
        hydro: 0.0020009981036856264
        hydro discharge: 6.065437910983327e-06
        nuclear: 0.1941214890377837
        oil: 8.703409839368813e-05
        solar: 0.012773471837065283
        unknown: 0.034459262086145304
        wind: 0.00013250843062965434
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
