bounding_box:
  - - -86.49625
    - 25.7531500000001
  - - -79.99125
    - 31.214009
capacity:
  battery storage: 0
  biomass: 255.2
  coal: 1478.4
  gas: 11223.9
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 1329.7
  solar: 745.3
  unknown: 18.8
  wind: 0
comment: Duke Energy Florida Inc
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 390.4456391861383
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 376.871882256667
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.0456850297263
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 411.7071924468364
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 521.6312947
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 423.934686
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 390.4456391861383
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 376.871882256667
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.0456850297263
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 411.7071924468364
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 1162.940076
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 543.5831773185287
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 572.1600047
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 581.6312947
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 543.934686
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 543.5831773185287
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1406.940076
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.14978891436787775
        gas: 0.7681544524631483
        geothermal: 0.0
        hydro: 0.005891410827868864
        hydro discharge: 8.088163884311528e-06
        nuclear: 0.027432389209777995
        oil: 0.0007037995925640236
        solar: 0.024862854842791608
        unknown: 0.02314829069380604
        wind: 9.860852075055026e-06
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
