bounding_box:
  - - -158.7789330139999
    - 20.75418992400006
  - - -157.14716739499988
    - 22.209850429000085
capacity:
  battery storage: 186
  biomass: 157.7
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 0
  oil: 1528.9
  solar: 201.1
  unknown: 0
  wind: 126.6
contributors:
  - kepiej
  - systemcatch
  - KabelWlan
  - danielmatsuda
  - brandongalbraith
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.5925224742688
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 416.698742219887
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 401.49743615810416
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1088.282256
    hydro discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.5925224742688
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 416.698742219887
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 401.49743615810416
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 742.1719304
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 923.678588772847
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 980.1789569
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1148.282256
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 923.678588772847
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 986.1719304
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.06067892277497898
        coal: 0.16436354714604337
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6832088906658947
        solar: 0.04862796250972639
        unknown: 0.0
        wind: 0.04317213987789937
flag_file_name: us.png
parsers:
  production: US_HI.fetch_production
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: Pacific/Honolulu
