bounding_box:
  - - -156.5601639279999
    - 18.40611714300016
  - - -154.31406356599993
    - 20.763429107000178
emissionFactors:
  direct:
    geothermal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    oil:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 785.7600688
  lifecycle:
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    geothermal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 38.0
    oil:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1029.7600688
flag_file_name: us.png
timezone: Pacific/Honolulu
