bounding_box:
  - - -90.88416
    - 34.3029500000001
  - - -73.39368
    - 43.00836
capacity:
  battery storage: 306.7
  biomass: 2328.8
  coal: 49012.9
  gas: 102052.7
  geothermal: 0
  hydro: 3311.2
  hydro storage: 5103.3
  nuclear: 34466.6
  oil: 6088.6
  solar: 6570.3
  unknown: 133.2
  wind: 10662.2
comment: Pjm Interconnection, Llc
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 326.5009214195872
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 323.1715360400933
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 299.9994377848068
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 314.378697647263
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 970.4739304
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 398.3043939
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 326.5009214195872
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 323.1715360400933
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 299.9994377848068
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 314.378697647263
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 751.5213327
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 441.8625978766893
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 515.9462429
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1049.3545804
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 518.3043938999999
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 441.8625978766893
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 995.5213327
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.82
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 1.2630739183978508e-11
        biomass: 3.973630547279639e-08
        coal: 0.22054393145646903
        gas: 0.3735906856418669
        geothermal: 0.0
        hydro: 0.020598013710036278
        hydro discharge: 9.345673383313458e-05
        nuclear: 0.329173942677495
        oil: 0.002739914533843371
        solar: 0.0072206054993883455
        unknown: 0.012931991976031872
        wind: 0.0331088282441298
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  price: US_PJM.fetch_price
  production: US_PJM.fetch_production
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
