bounding_box:
  - - -98.45079
    - 34.168033532
  - - -88.5987499999999
    - 41.779649115
capacity:
  battery storage: 0
  biomass: 4
  coal: 2481.7
  gas: 3056.5
  geothermal: 0
  hydro: 30
  hydro storage: 31
  nuclear: 0
  oil: 164.7
  solar: 2.5
  unknown: 0
  wind: 941.4
comment: Associated Electric Cooperative, Inc.
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 571.1170200316024
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 535.3321359247858
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 501.02724448006256
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 506.6284280818978
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 950.6306844
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 400.7407839
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 571.1170200316024
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 535.3321359247858
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 501.02724448006256
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 506.6284280818978
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 670.3401023258247
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 988.4513953999999
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 520.7407839
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 670.3401023258247
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.66
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.8023258523502484e-05
        coal: 0.5423580318736348
        gas: 0.22217527603979018
        geothermal: 2.592423199727177e-08
        hydro: 0.07000883841949739
        hydro discharge: 2.1199331649381914e-07
        nuclear: 0.009824642929423227
        oil: 2.454941143586806e-05
        solar: 0.00022531920800596513
        unknown: 0.0172209291789073
        wind: 0.1382666676564148
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Central
