bounding_box:
  - - -107.862115248933
    - 28.4286900252724
  - - -81.9130970652477
    - 49.884274119856
capacity:
  battery storage: 68.2
  biomass: 2487.4
  coal: 57162.9
  gas: 83349.6
  geothermal: 0
  hydro: 2467.3
  hydro storage: 2416.8
  nuclear: 13080.8
  oil: 5025.3
  solar: 3414.8
  unknown: 605.8
  wind: 29061
comment: Midcontinent Independent Transmission System Operator, Inc..
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 463.5439164156875
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 410.03298675919297
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 370.0323935596471
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 398.6722582688924
    biomass:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 139.1151962
    coal:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1014.733013
    gas:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 409.968837
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 463.5439164156875
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 410.03298675919297
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 370.0323935596471
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 398.6722582688924
    oil:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 922.7890878
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 533.2061713878306
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 479.90089944064755
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 439.06055345228873
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 465.51623295234066
    coal:
      datetime: '2020-01-01'
      source: 'Oberschelp, Christopher, et al. "Global emission hotspots of coal power
        generation.", https://drive.google.com/file/d/1XLg4fJ9_Bv9AfUda6yQlKeQ7vDwnUsaO/view?usp=sharing;
        eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1077.412392
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 533.2061713878306
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 479.90089944064755
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 439.06055345228873
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 465.51623295234066
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 26.45
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionPerModeForecast: US_MISO.fetch_wind_forecast
timezone: US/Central
