bounding_box:
  - - -115.80505
    - 32.97563
  - - -104.15314
    - 45.5057600000001
capacity:
  battery storage: 0
  biomass: 15.3
  coal: 5015.6
  gas: 3792.1
  geothermal: 83.8
  hydro: 271.7
  hydro storage: 0
  nuclear: 0
  oil: 30.4
  solar: 1627.9
  unknown: 52.8
  wind: 3193.3
comment: Pacificorp - East
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 525.929110346553
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 499.7763522049775
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 470.8378022801315
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 447.0277441701108
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1048.49561
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 405.722707
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 32.63419569
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 525.929110346553
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 499.7763522049775
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 470.8378022801315
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 447.0277441701108
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 639.8317920706698
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1107.353715
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 525.722707
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 70.63419569
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 639.8317920706698
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.475
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 1.9510470369741808e-07
        biomass: 0.0001926635698192392
        coal: 0.4859818651289909
        gas: 0.1772756958050386
        geothermal: 1.1654119513499041e-05
        hydro: 0.07373646797244078
        hydro discharge: 9.732590908379601e-06
        nuclear: 0.005183687338181877
        oil: 0.00023595700029813615
        solar: 0.06694383564363586
        unknown: 0.018652198106202545
        wind: 0.17202047499523967
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
