bounding_box:
  - - -80.26197
    - 39.99603
  - - -71.35625
    - 45.51097
capacity:
  battery storage: 65.6
  biomass: 517.7
  coal: 0
  gas: 27101.2
  geothermal: 0
  hydro: 4690.2
  hydro storage: 1240
  nuclear: 3398.4
  oil: 3853.7
  solar: 749.1
  unknown: 20
  wind: 2192.9
comment: New York Independent System Operator
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
  - brandongalbraith
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 168.63187033920536
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 180.25650620309392
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1095.578562
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 412.8877102
    hydro discharge:
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 168.63187033920536
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 180.25650620309392
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 662.0576145
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 266.28720998594736
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 667.6942738
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1179.0563129999998
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 532.8877102
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 266.28720998594736
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 906.0576145
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 4.466848291645783e-06
        biomass: 0.0020788498474700354
        coal: 0.019449970743529506
        gas: 0.42217852676771495
        geothermal: 1.2609286587518547e-06
        hydro: 0.2532193834568092
        hydro discharge: 8.66439618901438e-06
        nuclear: 0.24999899256426106
        oil: 0.0002357772783840252
        solar: 0.0007832537754805805
        unknown: 0.016115275134822374
        wind: 0.035959274617650035
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: US_NY.fetch_production
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
