bounding_box:
  - - -116.5492
    - 43.3016500000001
  - - -103.53947
    - 49.5011000000001
capacity:
  battery storage: 0
  biomass: 0
  coal: 1814.7
  gas: 259.6
  geothermal: 0
  hydro: 668.7
  hydro storage: 0
  nuclear: 0
  oil: 72.7
  solar: 17
  unknown: 0
  wind: 452.9
comment: Northwestern Energy (Nwmt)
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 517.3730453475288
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 502.3993935271729
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 401.18295440210744
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.7591280972269
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1063.960044
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 655.0343565
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 517.3730453475288
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 502.3993935271729
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 401.18295440210744
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.7591280972269
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 825.7991359
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 690.0368231558688
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1070.1093959999998
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 775.0343565
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 690.0368231558688
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1069.7991359
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 1.5296502009687276e-08
        biomass: 0.00012255017533619925
        coal: 0.591464453441105
        gas: 0.02977583698839574
        geothermal: 3.284248960903444e-06
        hydro: 0.2228081950224896
        hydro discharge: 1.970549376542067e-07
        nuclear: 0.0022588362513589915
        oil: 0.02656009116225709
        solar: 0.0034945425711499166
        unknown: 0.0009298788561400688
        wind: 0.12264661978137031
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
