bounding_box:
  - - -109.559308887
    - 35.7175500000001
  - - -102.094762152
    - 41.7250704890001
capacity:
  battery storage: 2
  biomass: 30.8
  coal: 2946.6
  gas: 6510
  geothermal: 0
  hydro: 55.2
  hydro storage: 300
  nuclear: 0
  oil: 33.2
  solar: 876
  unknown: 0
  wind: 4490.8
comment: Public Service Company Of Colorado
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 512.3614391161192
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 470.40451449537994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 395.97864367883375
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 409.8420322029403
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1078.74216
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 480.4971119
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 512.3614391161192
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 470.40451449537994
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 395.97864367883375
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 409.8420322029403
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 613.7060455510662
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1117.644366
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 600.4971118999999
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 613.7060455510662
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 8.270263430862999e-10
        biomass: 3.7042509906835375e-06
        coal: 0.4037728741631222
        gas: 0.26315137192566457
        geothermal: 2.6671599564533172e-08
        hydro: 0.01573855073305861
        hydro discharge: 7.002845560083245e-07
        nuclear: 0.0007185444706373269
        oil: 3.4469010683736574e-05
        solar: 0.029488466589072455
        unknown: 4.6296727929385286e-05
        wind: 0.2870451980008962
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
