bounding_box:
  - - -120.819941629
    - 46.7200530000001
  - - -118.335197
    - 49.500448
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 774
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Pud No. 1 Of Douglas County
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 5.275599473576463
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 5.664354526024614
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 1.3722941731782523
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 2.9692242958240866
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 5.275599473576463
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 5.664354526024614
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 1.3722941731782523
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 2.9692242958240866
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 27.482111221792938
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 27.482111221792938
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 5.476012327997208e-08
        biomass: 0.00013911560409625632
        coal: 0.0016808122021484888
        gas: 0.0029373529255098045
        geothermal: 3.061588710652985e-06
        hydro: 0.9881321869550435
        hydro discharge: 2.489096512726004e-08
        nuclear: 0.0034255692937089073
        oil: 4.8960528405320495e-05
        solar: 0.00016445460659580708
        unknown: 0.0006133631626659419
        wind: 0.0031646472626658917
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Pacific
