bounding_box:
  - - -121.98446
    - 34.50232
  - - -111.0849
    - 42.5017700000001
capacity:
  battery storage: 100
  biomass: 35.2
  coal: 809
  gas: 7828.2
  geothermal: 785.8
  hydro: 12.8
  hydro storage: 0
  nuclear: 0
  oil: 21
  solar: 2346.7
  unknown: 7.5
  wind: 150
comment: Nevada Power Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 402.2738093042844
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 382.74370390170117
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 358.66689177867426
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.7785287366052
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1092.399419
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 405.9274374
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 14.37975781
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 402.2738093042844
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 382.74370390170117
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 358.66689177867426
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.7785287366052
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 508.9334157047475
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1179.761649
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 525.9274373999999
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 52.37975781
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 508.9334157047475
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 2.4442634784952834e-06
        biomass: 0.0003460606001801986
        coal: 0.1409747977612679
        gas: 0.5519692748497959
        geothermal: 0.000128139169858204
        hydro: 0.07779278729914249
        hydro discharge: 5.567543557932234e-05
        nuclear: 0.017438876718490783
        oil: 7.566317806286297e-05
        solar: 0.09570843951037572
        unknown: 0.07943114503169377
        wind: 0.03643424977937991
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
