bounding_box:
  - - -124.98038
    - 38.66544
  - - -115.96327
    - 47.5893300000001
capacity:
  battery storage: 0
  biomass: 161
  coal: 2441.9
  gas: 621.2
  geothermal: 3.7
  hydro: 1127.6
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 411.7
  unknown: 0
  wind: 694.3
comment: Pacificorp - West
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.51632672419134
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 310.368608788063
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 246.15102694995622
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 270.51293346887013
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 400.6744614
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.51632672419134
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 310.368608788063
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 246.15102694995622
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 270.51293346887013
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 378.5766325490713
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 355.2770809756254
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 289.751131181963
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 315.24940626350605
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 29.16184216
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 811.451201
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 520.6744613999999
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 378.5766325490713
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 355.2770809756254
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 289.751131181963
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 315.24940626350605
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.575
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
