bounding_box:
  - - -120.542866
    - 46.125243
  - - -118.473872746
    - 48.462236509
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 1236
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Public Utility District No. 2 Of Grant County, Washington
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 34.035926015825474
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 22.669662464776113
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 13.741517196675936
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 17.147749384136038
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 34.035926015825474
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 22.669662464776113
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 13.741517196675936
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 17.147749384136038
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 41.219175701670366
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 41.219175701670366
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 2.634837362907216e-08
        biomass: 0.00026120899336741174
        coal: 0.004455657531568426
        gas: 0.022190891859072737
        geothermal: 1.923431274922268e-06
        hydro: 0.9397200432605164
        hydro discharge: 9.485414506465979e-08
        nuclear: 0.006626637046410551
        oil: 0.00011736619549333906
        solar: 0.0005786155545691505
        unknown: 0.004422221445433134
        wind: 0.022049237732768123
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Pacific
