bounding_box:
  - - -113.348433684
    - 43.730745552
  - - -102.051328941
    - 49.1340949710001
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 969.1
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 77.6
comment: Western Area Power Administration Ugp West
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 247.49640235158822
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 279.6956491387049
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 236.95859846184595
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 236.42339916047612
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 247.49640235158822
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 279.6956491387049
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 236.95859846184595
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 236.42339916047612
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 350.86841690436955
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 776.557703
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 350.86841690436955
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0001739541570315472
        coal: 0.26307923818255347
        gas: 0.0942631368628971
        geothermal: 6.480080352996378e-07
        hydro: 0.42025759519418043
        hydro discharge: 0.0
        nuclear: 0.027869637583506034
        oil: 0.004197916054159072
        solar: 0.0015858676647590429
        unknown: 0.0014880184514287978
        wind: 0.18743901224375184
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Mountain
