bounding_box:
  - - -113.660743713
    - 47.4742527010001
  - - -111.05112648
    - 49.491411209
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 210
comment: Naturener Power Watch, Llc (Gwa)
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  production: 30
emissionFactors:
  lifecycle:
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650.0
flag_file_name: us.png
parsers:
  production: EIA.fetch_production_mix
timezone: US/Mountain
