bounding_box:
  - - -116.5492
    - 43.3016500000001
  - - -103.53947
    - 49.5011000000001
comment: Northwestern Energy (Nwmt)
bypassAggregationChecks: true
hasGeometry: true
timezone: US/Mountain
subZoneNames:
  - US-NW-NWMT
  - US-NW-GWA
  - US-NW-WWA