bounding_box:
  - - -121.680713
    - 46.760889
  - - -119.359734
    - 49.050725
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 1988.2
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Public Utility District No. 1 Of Chelan County
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 2.6616814565395046
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 2.3041693101987883
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 2.4969594481122965
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 1.3005033418468372
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 2.6616814565395046
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 2.3041693101987883
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 2.4969594481122965
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 1.3005033418468372
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 25.414633151379807
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 25.414633151379807
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 2.1462035839679002e-08
        biomass: 3.711322547576491e-05
        coal: 0.0005916761350461906
        gas: 0.0012858281257178883
        geothermal: 1.1535844263827463e-06
        hydro: 0.9930386599031852
        hydro discharge: 1.0731017919839501e-08
        nuclear: 0.0009079460606886602
        oil: 1.5737037779444627e-05
        solar: 7.402256161105289e-05
        unknown: 0.00037006451847462513
        wind: 0.003761377380663583
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Pacific
