bounding_box:
  - - -122.936059783
    - 46.955507
  - - -121.725915999
    - 48.277929
capacity:
  battery storage: 5
  biomass: 4.6
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 2007.4
  hydro storage: 0
  nuclear: 0
  oil: 10
  solar: 0
  unknown: 0
  wind: 0
comment: Seattle City Light
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 66.57863298647425
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 50.23995226838326
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 27.595604864062736
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 33.575020236312795
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 66.57863298647425
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 50.23995226838326
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 27.595604864062736
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 33.575020236312795
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 99.31349067162931
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 80.95425524778744
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 55.94689331623827
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 62.780638512347714
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 99.31349067162931
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 80.95425524778744
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 55.94689331623827
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 62.780638512347714
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Pacific
