bounding_box:
  - - -119.851352692
    - 44.7463779450001
  - - -118.363136292
    - 46.366308212
comment: Gridforce Energy Management, Llc
contributors:
  - systemcatch
  - robertahunt
delays:
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 368.2789560199815
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 368.9741317593273
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 494.01178620699216
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 382.0289183925492
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 395.5270557
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 368.2789560199815
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 368.9741317593273
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 494.01178620699216
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 382.0289183925492
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.0562626185262
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 515.5270557
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.0562626185262
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.4425178332709873e-06
        coal: 0.21277406330695575
        gas: 0.607427839031951
        geothermal: 3.7000406634468914e-09
        hydro: 0.0009197516680708322
        hydro discharge: 0.0
        nuclear: 0.00010494129330481343
        oil: 1.3386747120350853e-06
        solar: 0.02771352657165702
        unknown: 2.0436804600482556e-05
        wind: 0.1510388581970516
flag_file_name: us.png
parsers:
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
