bounding_box:
  - - -125.23688
    - 39.61659
  - - -105.50971
    - 49.50244
capacity:
  battery storage: 3
  biomass: 419.5
  coal: 729.9
  gas: 2277.5
  geothermal: 18
  hydro: 21708.1
  hydro storage: 314
  nuclear: 1200
  oil: 0
  solar: 87.9
  unknown: 0
  wind: 3397.5
comment: Bonneville Power Administration
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 82.7869008837892
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 69.96183233976832
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 37.47489940701006
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 53.50440564280603
    biomass:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 85.91723542
    coal:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1134.898924
    gas:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 394.4247594
    geothermal:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 0.0
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 82.7869008837892
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 69.96183233976832
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 37.47489940701006
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 53.50440564280603
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 117.62690701804988
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 103.37311717623633
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 67.08189685920867
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 85.70421092545492
    coal:
      datetime: '2020-01-01'
      source: 'IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 1194.898924
    hydro discharge:
      - datetime: '2018-01-01'
        source: electricityMap, 2018 average
        value: 117.62690701804988
      - datetime: '2019-01-01'
        source: electricityMap, 2019 average
        value: 103.37311717623633
      - datetime: '2020-01-01'
        source: electricityMap, 2020 average
        value: 67.08189685920867
      - datetime: '2021-01-01'
        source: electricityMap, 2021 average
        value: 85.70421092545492
    solar:
      datetime: '2021-01-01'
      source: INCER ACV, https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
      value: 32.8
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
timezone: US/Pacific
