bounding_box:
  - - -124.225142777
    - 44.2721814650001
  - - -121.156917718
    - 46.4057731890001
capacity:
  battery storage: 5
  biomass: 15.9
  coal: 0
  gas: 2115.3
  geothermal: 0
  hydro: 676.2
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 135.5
  unknown: 0
  wind: 716.5
comment: Portland General Electric Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 155.00851509578533
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 132.51412996153388
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 99.82584134645398
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 125.68350934154255
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1040.946037
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 465.3652195
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 155.00851509578533
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 132.51412996153388
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 99.82584134645398
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 125.68350934154255
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 208.1490155546106
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 181.73506222776373
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 145.54691797102316
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 176.8878423289599
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1100.946037
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 585.3652195
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 208.1490155546106
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 181.73506222776373
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 145.54691797102316
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 176.8878423289599
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 30.16666667
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
