bounding_box:
  - - -114.55
    - 35.43059
  - - -95.95176
    - 48.07463
capacity:
  battery storage: 8.2
  biomass: 3.2
  coal: 4294.3
  gas: 1931.8
  geothermal: 0
  hydro: 704.3
  hydro storage: 208.5
  nuclear: 0
  oil: 158.8
  solar: 199.2
  unknown: 11.5
  wind: 1091.2
comment: Western Area Power Administration - Rocky Mountain Region
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 521.4568598921377
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 511.2777405120074
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 513.7422117905244
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 515.7360263413145
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1107.615308
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 451.7150314
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 521.4568598921377
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 511.2777405120074
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 513.7422117905244
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 515.7360263413145
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 953.0188558
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 766.9391259296401
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1125.725068
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 571.7150314
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 766.9391259296401
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1197.0188558
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 1.1646032008790393e-08
        biomass: 1.5047089285071788e-05
        coal: 0.6611531269097868
        gas: 0.02937752917631008
        geothermal: 3.5437211683890764e-07
        hydro: 0.17463885493567977
        hydro discharge: 1.2029935135365874e-05
        nuclear: 0.003174585210400739
        oil: 5.671076879651942e-05
        solar: 0.0077608075889321225
        unknown: 0.0003080433696485103
        wind: 0.12350465671685011
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
