bounding_box:
  - - -120.44398
    - 41.48796
  - - -111.08807
    - 47.1707900000001
capacity:
  battery storage: 0
  biomass: 24.6
  coal: 6.2
  gas: 774.4
  geothermal: 33
  hydro: 2028.7
  hydro storage: 0
  nuclear: 0
  oil: 5
  solar: 318.3
  unknown: 15.9
  wind: 716.8
comment: Idaho Power Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 296.50732153263004
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 271.0584192983204
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.007396607415505
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 248.5579129438617
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 434.3409586
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 0.0
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 296.50732153263004
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 271.0584192983204
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.007396607415505
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 248.5579129438617
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.7149634852897
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 554.3409586
    geothermal:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 38.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.7149634852897
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 7.43035896064139e-08
        biomass: 0.0002362149641375101
        coal: 0.2050220992635413
        gas: 0.20451758999884692
        geothermal: 5.224918341731015e-06
        hydro: 0.33211351827221586
        hydro discharge: 3.2225742010781724e-06
        nuclear: 0.0043934287006146
        oil: 0.0002387418365810882
        solar: 0.06078957471102096
        unknown: 0.029083564844054652
        wind: 0.16387553102986702
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
