bounding_box:
  - - -120.54268
    - 44.57814
  - - -113.68675
    - 49.50073
capacity:
  battery storage: 0
  biomass: 199.9
  coal: 0
  gas: 563.7
  geothermal: 0
  hydro: 1173.9
  hydro storage: 0
  nuclear: 0
  oil: 2.8
  solar: 19.2
  unknown: 0
  wind: 249.3
comment: Avista Corporation
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 192.24523949942247
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 156.7095216675603
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 121.19864096056943
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 135.69137283431053
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 393.6395083
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 192.24523949942247
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 156.7095216675603
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 121.19864096056943
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 135.69137283431053
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 248.44347013173143
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 207.1104514026927
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 167.4007806240946
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 183.61633166677058
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 205.8471989
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 513.6395083
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 248.44347013173143
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 207.1104514026927
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 167.4007806240946
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 183.61633166677058
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Pacific
