bounding_box:
  - - -124.21924
    - 30.83201
  - - -105.02991
    - 44.1167400000001
capacity:
  battery storage: 90
  biomass: 0
  coal: 0
  gas: 2407.3
  geothermal: 0
  hydro: 5610.5
  hydro storage: 65.2
  nuclear: 0
  oil: 4.5
  solar: 302.2
  unknown: 0
  wind: 350
comment: Western Area Power Administration - Desert Southwest Region
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 458.1928165758674
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 261.74465469059044
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 298.51377588409974
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 277.55427438086537
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 517.3221021
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 458.1928165758674
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 261.74465469059044
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 298.51377588409974
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 277.55427438086537
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 387.9264386600192
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 817.120985
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 637.3221021
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 387.9264386600192
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 9.270180135786066e-06
        biomass: 0.0004522981381489003
        coal: 0.1516476167462289
        gas: 0.34840775909172506
        geothermal: 0.0007962904891875693
        hydro: 0.27939103091269907
        hydro discharge: 0.0003697690106543309
        nuclear: 0.1030788442717644
        oil: 3.333340963111223e-05
        solar: 0.03844026358048691
        unknown: 0.007971362500666244
        wind: 0.06941333983826398
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Arizona
