bounding_box:
  - - -113.83417
    - 32.00496
  - - -110.438901961
    - 34.54817
capacity:
  battery storage: 45
  biomass: 0
  coal: 821.8
  gas: 8265.6
  geothermal: 0
  hydro: 92.3
  hydro storage: 154.1
  nuclear: 4209.6
  oil: 0
  solar: 460
  unknown: 0
  wind: 63
comment: Salt River Project
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 234.7223073963906
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 208.17859641915237
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 217.92328237284988
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 209.6509902146305
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1218.520193
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 376.0036772
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 234.7223073963906
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 208.17859641915237
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 217.92328237284988
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 209.6509902146305
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 301.1148243883558
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1278.520193
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 496.0036772
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 301.1148243883558
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 5.298218098349407e-07
        biomass: 2.476086382233557e-05
        coal: 0.06695769303648147
        gas: 0.4204770937946904
        geothermal: 4.3226815052572826e-05
        hydro: 0.01759550645428339
        hydro discharge: 0.001347392380042143
        nuclear: 0.4664796846521921
        oil: 1.4181039200532568e-06
        solar: 0.017749440673082414
        unknown: 0.0006973867001293964
        wind: 0.008626087900728219
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Arizona
