bounding_box:
  - - -85.61569
    - 30.211187
  - - -83.357543
    - 33.075117
capacity:
  battery storage: 0
  biomass: 1.7
  coal: 0
  gas: 0
  geothermal: 0
  hydro: 1081.9
  hydro storage: 328
  nuclear: 0
  oil: 0
  solar: 25.4
  unknown: 0
  wind: 0
comment: Southeastern Power Administration
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 68.84128617219797
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 57.19191602228616
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 41.53156154966831
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 56.222867961402216
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 68.84128617219797
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 57.19191602228616
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 41.53156154966831
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 56.222867961402216
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 21.009397412365136
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 21.009397412365136
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.07337740561187013
        gas: 0.07838695460555312
        geothermal: 0.0
        hydro: 0.7011488173938593
        hydro discharge: 0.00288379609225797
        nuclear: 0.13393565447333627
        oil: 1.4690759512266785e-06
        solar: 0.007555457617158807
        unknown: 0.0025165271044512998
        wind: 1.4690759512266785e-05
flag_file_name: us.png
parsers:
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: US/Eastern
