bounding_box:
  - - -108.7302
    - 26.75944
  - - -98.29803
    - 33.98024
capacity:
  battery storage: 0
  biomass: 3.2
  coal: 0
  gas: 1922.9
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 130.3
  unknown: 0
  wind: 0
comment: El Paso Electric Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 393.18214526747084
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 381.5598631025588
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.5133836327625
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 379.20992981519225
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 545.8860298
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 393.18214526747084
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 381.5598631025588
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.5133836327625
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 379.20992981519225
  lifecycle:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 492.04108039116386
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 478.16327775843206
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.3934116074368
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 473.57012018273264
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 665.8860298
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 492.04108039116386
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 478.16327775843206
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.3934116074368
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 473.57012018273264
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00018692835707358646
        coal: 0.16874884141944566
        gas: 0.7145623967400215
        geothermal: 3.1989988359432235e-05
        hydro: 0.006934762594149536
        hydro discharge: 7.656311849505005e-05
        nuclear: 0.02735326324211385
        oil: 0.0003249911108190459
        solar: 0.04052535889169227
        unknown: 0.000674228057330626
        wind: 0.04058072515803051
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00027064244571817285
        coal: 0.1640690998642903
        gas: 0.6913959743406202
        geothermal: 4.853531990836573e-05
        hydro: 0.009231558919876114
        hydro discharge: 0.00013058904677284254
        nuclear: 0.02985889148540449
        oil: 0.0004617169654028869
        solar: 0.049771518755062125
        unknown: 0.001427239330392389
        wind: 0.05333353637561084
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
