bounding_box:
  - - -90.5406
    - 29.42398
  - - -80.251429
    - 35.5013030000001
capacity:
  battery storage: 42.2
  biomass: 1979.5
  coal: 16164.8
  gas: 34941.7
  geothermal: 0
  hydro: 3310.4
  hydro storage: 1306.6
  nuclear: 6054.4
  oil: 1284.8
  solar: 3662
  unknown: 0
  wind: 0
comment: Southern Company Services, Inc. - Trans
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 387.86457393118644
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 363.98213837874664
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 330.5848387522014
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 348.1291170995103
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 865.2241498
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 403.2500634
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 387.86457393118644
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 363.98213837874664
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 330.5848387522014
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 348.1291170995103
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 569.2843708
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 466.40479434576497
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 72.20359898
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 943.0750138
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 523.2500634
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 466.40479434576497
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 813.2843708
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.6197169371510176e-07
        coal: 0.2080956584114764
        gas: 0.49148314652948866
        geothermal: 0.0
        hydro: 0.05149190112101555
        hydro discharge: 0.00033576422771279914
        nuclear: 0.2136947001302248
        oil: 2.4946863080674378e-05
        solar: 0.023465308513822107
        unknown: 0.011075544332621392
        wind: 0.00034126769934405204
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Eastern
