bounding_box:
  - - -113.26607132
    - 31.246901321
  - - -111.760446548
    - 33.5380344390001
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 619
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Gila River Power, Llc
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  production: 30
flag_file_name: us.png
parsers:
  production: EIA.fetch_production_mix
timezone: US/Arizona
