bounding_box:
  - - -108.7302
    - 26.75944
  - - -98.29803
    - 33.98024
capacity:
  battery storage: 0
  biomass: 3.2
  coal: 0
  gas: 1922.9
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 130.3
  unknown: 0
  wind: 0
comment: El Paso Electric Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 393.18214526747084
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 381.5598631025588
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.5133836327625
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 379.20992981519225
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 545.8860298
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 393.18214526747084
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 381.5598631025588
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 383.5133836327625
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 379.20992981519225
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 641.9435707652311
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 665.8860298
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 641.9435707652311
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 9.025386290669875e-08
        biomass: 8.96405994792558e-06
        coal: 0.18330897545496094
        gas: 0.6527233928988425
        geothermal: 1.1751515790774776e-05
        hydro: 0.00629894784464964
        hydro discharge: 0.00010040626538289588
        nuclear: 0.01932987809687284
        oil: 3.31972221383742e-06
        solar: 0.059661301297065907
        unknown: 0.0014996790138722235
        wind: 0.07705298347352142
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
