bounding_box:
  - - -114.764827728
    - 34.168836594
  - - -112.998666763
    - 35.717744827
capacity:
  battery storage: 0
  biomass: 0
  coal: 0
  gas: 655
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Griffith Energy, Llc
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  production: 30
emissionFactors:
  direct:
    gas:
      datetime: '2020-01-01'
      source: 'eGrid 2020: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
      value: 390.1784429
  lifecycle:
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014, https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7;
        IPCC 2014
      value: 820.0
flag_file_name: us.png
parsers:
  production: EIA.fetch_production_mix
timezone: US/Arizona
