bounding_box:
  - - -88.9596785776442
    - 29.339638675596
  - - -84.3581394658229
    - 34.4502982778481
capacity:
  battery storage: 0
  biomass: 4.8
  coal: 0
  gas: 1330
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 0
  solar: 0
  unknown: 0
  wind: 0
comment: Powersouth Energy Cooperative
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 483.75390411266727
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 436.137933842743
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 390.3629582112602
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 366.55441599595804
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1196.66141
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 404.1054386
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 483.75390411266727
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 436.137933842743
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 390.3629582112602
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 366.55441599595804
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 521.2200312142762
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1310.312319
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 524.1054386000001
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 521.2200312142762
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.9837240945072053
        geothermal: 0.0
        hydro: 0.008503295011414636
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.00777261048138002
        wind: 0.0
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Central
