bounding_box:
  - - -115.31829
    - 30.8336654
  - - -108.777145881
    - 36.784585904
capacity:
  battery storage: 2
  biomass: 33.4
  coal: 2062.1
  gas: 2714.6
  geothermal: 0
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 123.8
  solar: 756.6
  unknown: 0
  wind: 374.3
comment: Arizona Public Service Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.92556312834165
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 234.48835768785938
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 360.1672900365513
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 329.2721193872668
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1055.103824
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 371.3656203
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 262.92556312834165
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 234.48835768785938
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 360.1672900365513
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 329.2721193872668
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.61015068419204
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 34.52335329
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1072.158303
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 491.3656203
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.61015068419204
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 1.184207731843033e-06
        biomass: 2.6021598027496122e-05
        coal: 0.21699578887260643
        gas: 0.4049420657892342
        geothermal: 3.541056074369383e-05
        hydro: 0.017074653251840124
        hydro discharge: 0.0008175941475170763
        nuclear: 0.2795163713953564
        oil: 8.968627439082357e-06
        solar: 0.04625073953725447
        unknown: 0.010039607592683613
        wind: 0.024298130475104016
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Arizona
