bounding_box:
  - - -123.550316649
    - 30.83222
  - - -101.52796
    - 44.59554275
capacity:
  battery storage: 1.8
  biomass: 14.6
  coal: 573
  gas: 1833.9
  geothermal: 19.2
  hydro: 0
  hydro storage: 0
  nuclear: 0
  oil: 30.4
  solar: 419.9
  unknown: 1.1
  wind: 2424
comment: Public Service Company Of New Mexico
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
  - brandongalbraith
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 461.5385986022287
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.77131560435174
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 433.84188686987903
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 422.79226747577917
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1202.427801
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 412.1499722
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 461.5385986022287
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.77131560435174
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 433.84188686987903
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 422.79226747577917
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 677.0004108933182
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1246.197747
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 532.1499722
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 677.0004108933182
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 7.971373353265002e-08
        biomass: 3.874596260751892e-06
        coal: 0.4220726207071528
        gas: 0.2842637412047576
        geothermal: 4.490257649525338e-06
        hydro: 0.009299115827648724
        hydro discharge: 0.0002427512151048489
        nuclear: 0.01826379014220589
        oil: 4.13239386707025e-06
        solar: 0.060853018969143045
        unknown: 0.0034331645009460067
        wind: 0.2015590525638787
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Mountain
