bounding_box:
  - - -104.48406
    - 25.3370600000001
  - - -93.2943099999999
    - 36.55797
capacity:
  battery storage: 780
  biomass: 189.5
  coal: 15217.2
  gas: 65534.7
  geothermal: 0
  hydro: 569.7
  hydro storage: 0
  nuclear: 5138.6
  oil: 117
  solar: 10047.2
  unknown: 234.7
  wind: 32699.2
comment: Electric Reliability Council Of Texas, Inc.
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.2665017887658
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 331.3032294168079
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 307.5256999044057
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 301.921088325611
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1043.400889
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 393.100066
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.2665017887658
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 331.3032294168079
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 307.5256999044057
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 301.921088325611
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 1070.811109
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 428.8286615039803
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.4539605655
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1081.455715
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 513.100066
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 428.8286615039803
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 1314.811109
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.699271923729837e-06
        coal: 0.19252396325419224
        gas: 0.418260460555364
        geothermal: 2.785496967056957e-07
        hydro: 0.0013928784580988127
        hydro discharge: 1.7836149624404227e-10
        nuclear: 0.10324877356075696
        oil: 7.002090139334862e-06
        solar: 0.03879396735206749
        unknown: 0.0015180241712047652
        wind: 0.24425208187027933
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Central
