bounding_box:
  - - -90.849224442
    - 31.824126136000103
  - - -81.14647784
    - 38.101846827
capacity:
  battery storage: 1
  biomass: 288.9
  coal: 8593.9
  gas: 17502.6
  geothermal: 0
  hydro: 4871.8
  hydro storage: 1808.6
  nuclear: 8474.8
  oil: 74.6
  solar: 670
  unknown: 0
  wind: 28.8
comment: Tennessee Valley Authority
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
delays:
  consumption: 30
  consumptionForecast: 30
  production: 30
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 283.98299931476635
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 257.2468837277304
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 220.15206446184618
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 246.4290952696185
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1070.741206
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 391.2963051
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 283.98299931476635
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 257.2468837277304
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 220.15206446184618
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 246.4290952696185
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 472.7975672
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 364.57502733192445
    biomass:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 14.46015011
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 1152.251617
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 511.2963051
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 364.57502733192445
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 716.7975672
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.06666667
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.3512877399276507e-06
        coal: 0.19066058888018092
        gas: 0.2700887255399683
        geothermal: 6.245760553008274e-11
        hydro: 0.1193625037070939
        hydro discharge: 0.0012007719496972082
        nuclear: 0.40035491494369607
        oil: 5.272633584286267e-05
        solar: 0.004549205501967344
        unknown: 0.002267402950506192
        wind: 0.011748960510310807
flag_file_name: us.png
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: US/Central
