bounding_box:
  - - 55.497790533287294
    - 36.68830730933749
  - - 73.61853118531187
    - 46.06232808111943
capacity:
  solar:
  - datetime: '2024-08-30'
    source: 'The Ministry of Energy of the Republic of Uzbekistan'
    comment: https://gov.uz/oz/minenergy/news/view/29602
    value: 2300
  wind: 
  - datetime: '2024-08-30'
    source: 'The Ministry of Energy of the Republic of Uzbekistan'
    comment: https://gov.uz/oz/minenergy/news/view/29602
    value: 500
  hydro:
  - datetime: '2024-08-29'
    source: 'Statistics Agency under the President of the Republic of Uzbekistan'
    comment: https://stat.uz/uz/rasmiy-statistika/industry-2
    value: 2381
  gas:
  - datetime: '2024-08-29'
    source: 'Statistics Agency under the President of the Republic of Uzbekistan'
    comment: https://stat.uz/uz/rasmiy-statistika/industry-2
    value: 13874
country: UZ
region: Asia
timezone: Asia/Samarkand
