contributors:
  - alixunderplatz
  - MuffinCompiler
  - VIKTORVAV99

parsers:
  consumption: VN.fetch_consumption
  price: VN.fetch_price

bounding_box:
  - - 135.84
    - 33.82
  - - 138.72
    - 37.17

capacity:
  biomass: 356
  coal: 25820
  gas: 7398
  hydro: 22345
  oil: 1579
  solar: 16567
  unknown: 619
  wind: 4667

subZoneNames:
  - VN-N
  - VN-C
  - VN-S

timezone: Asia/Ho_Chi_Minh
