bounding_box:
  - - 20.013053
    - 41.848669
  - - 21.791473
    - 43.269883
capacity:
  coal: 1288
  hydro: 68
  solar: 10.002
  wind: 136
contributors:
  - veqtrus
delays:
  production: 48
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
  productionPerUnit: ENTSOE.fetch_production_per_units
timezone: Europe/Belgrade
