name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.check-frontend.outputs.any_changed }}
      markdown: ${{ steps.check-markdown.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check frontend files
        id: check-frontend
        uses: tj-actions/changed-files@v20
        with:
          files: |
            **/web/**/*
          files_ignore: |
            **/web/public/locales/*.json
            **/web/**/*.md
      - name: Check markdown files
        id: check-markdown
        uses: tj-actions/changed-files@v20
        with:
          files: |
            **/*.md
      - name: Log outputs
        run: |
          echo "frontend changed: ${{ steps.check-frontend.outputs.any_changed }}"
          echo "markdown changed: ${{ steps.check-markdown.outputs.any_changed }}"

  validate_local_links:
    name: Validate local links in markdown files
    needs: [setup]
    if: needs.setup.outputs.markdown != 'false'
    uses: ./.github/workflows/validate-local-links-in-md.yml

  cypress:
    name: Cypress
    needs: [setup]
    if: needs.setup.outputs.frontend != 'false'
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
