on:
  workflow_call:

jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mockserver
        run: |
          yarn install
        working-directory: ./mockserver
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./web
          start: yarn develop, yarn run mockserver
          wait-on: 'http://localhost:8080'
