on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './web/.node-version'
      - name: Restore node_modules
        id: cache-pnpm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            web/node_modules
            mockserver/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./pnpm-lock.yaml') }}
      - name: Install web dependencies
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./web
        run: pnpm run build
        env:
          VITE_PUBLIC_ELECTRICITYMAP_PUBLIC_TOKEN: '${{ secrets.VITE_PUBLIC_ELECTRICITYMAP_PUBLIC_TOKEN }}'
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          projectName: 'electricitymaps-staging'
          directory: ./web/dist
