name: ESLint

on:
  workflow_call:

jobs:
  eslint:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: |
          cd web
          yarn install --frozen-lockfile
      - name: Restore ESLint cache
        uses: actions/cache@v3
        with:
          path: ./web/node_modules/.cache/eslint/.eslintcache
          key: ${{ runner.os }}-eslint_cache-${{ github.ref_name }}-${{ github.job }}
          restore-keys: |
            ${{ runner.os }}-eslint_cache-${{ github.ref_name }}
      - name: ESLint
        run: |
          lint
