on:
  workflow_call:

jobs:
  jest-test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: yarn
        run: yarn test
        working-directory: ./web
