name: Python Formatting

on:
  workflow_call:

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - name: Install Dependencies
        run: |
          poetry install -E parsers --sync
      - name: Linting
        run: |
          poetry run lint
