name: Python Tests

on:
  workflow_call:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - name: Install libxml2-dev and tesseract-ocr
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev tesseract-ocr tesseract-ocr-eng
      - name: Install Poetry dependencies
        run: |
          poetry install -E parsers --sync
      - name: Run tests
        run: |
          poetry run test
